PROJECT ( MessageReceiverPlugin VERSION 7.11.1 LANGUAGES CXX )

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

SET (TMX_PLUGIN_NAME "MessageReceiver")
SET (CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules)



BuildTmxPlugin ()

TARGET_INCLUDE_DIRECTORIES ( ${PROJECT_NAME} PUBLIC
/opt/carma/include/stol-1609dot2-2022 )
TARGET_LINK_LIBRARIES ( ${PROJECT_NAME} tmxutils ) #libbotan-2)
