/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../J2735_R41_Source_mod.ASN"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#include "ComputedLane.h"

static asn_per_constraints_t asn_PER_type_offsetXaxis_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_offsetYaxis_constr_6 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_offsetXaxis_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ComputedLane__offsetXaxis, choice.small),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DrivenLineOffsetSm,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"small"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ComputedLane__offsetXaxis, choice.large),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DrivenLineOffsetLg,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"large"
		},
};
static asn_TYPE_tag2member_t asn_MAP_offsetXaxis_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* small */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* large */
};
static asn_CHOICE_specifics_t asn_SPC_offsetXaxis_specs_3 = {
	sizeof(struct ComputedLane__offsetXaxis),
	offsetof(struct ComputedLane__offsetXaxis, _asn_ctx),
	offsetof(struct ComputedLane__offsetXaxis, present),
	sizeof(((struct ComputedLane__offsetXaxis *)0)->present),
	asn_MAP_offsetXaxis_tag2el_3,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_offsetXaxis_3 = {
	"offsetXaxis",
	"offsetXaxis",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_offsetXaxis_constr_3,
	asn_MBR_offsetXaxis_3,
	2,	/* Elements count */
	&asn_SPC_offsetXaxis_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_offsetYaxis_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ComputedLane__offsetYaxis, choice.small),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DrivenLineOffsetSm,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"small"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ComputedLane__offsetYaxis, choice.large),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DrivenLineOffsetLg,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"large"
		},
};
static asn_TYPE_tag2member_t asn_MAP_offsetYaxis_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* small */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* large */
};
static asn_CHOICE_specifics_t asn_SPC_offsetYaxis_specs_6 = {
	sizeof(struct ComputedLane__offsetYaxis),
	offsetof(struct ComputedLane__offsetYaxis, _asn_ctx),
	offsetof(struct ComputedLane__offsetYaxis, present),
	sizeof(((struct ComputedLane__offsetYaxis *)0)->present),
	asn_MAP_offsetYaxis_tag2el_6,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_offsetYaxis_6 = {
	"offsetYaxis",
	"offsetYaxis",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_offsetYaxis_constr_6,
	asn_MBR_offsetYaxis_6,
	2,	/* Elements count */
	&asn_SPC_offsetYaxis_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ComputedLane_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ComputedLane, referenceLaneId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"referenceLaneId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ComputedLane, offsetXaxis),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_offsetXaxis_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"offsetXaxis"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ComputedLane, offsetYaxis),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_offsetYaxis_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"offsetYaxis"
		},
	{ ATF_POINTER, 4, offsetof(struct ComputedLane, rotateXY),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Angle,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rotateXY"
		},
	{ ATF_POINTER, 3, offsetof(struct ComputedLane, scaleXaxis),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Scale_B12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"scaleXaxis"
		},
	{ ATF_POINTER, 2, offsetof(struct ComputedLane, scaleYaxis),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Scale_B12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"scaleYaxis"
		},
	{ ATF_POINTER, 1, offsetof(struct ComputedLane, regional),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionalComputedLane,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"regional"
		},
};
static int asn_MAP_ComputedLane_oms_1[] = { 3, 4, 5, 6 };
static ber_tlv_tag_t asn_DEF_ComputedLane_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ComputedLane_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* referenceLaneId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* offsetXaxis */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* offsetYaxis */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* rotateXY */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* scaleXaxis */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* scaleYaxis */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* regional */
};
static asn_SEQUENCE_specifics_t asn_SPC_ComputedLane_specs_1 = {
	sizeof(struct ComputedLane),
	offsetof(struct ComputedLane, _asn_ctx),
	asn_MAP_ComputedLane_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_ComputedLane_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	6,	/* Start extensions */
	8	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ComputedLane = {
	"ComputedLane",
	"ComputedLane",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ComputedLane_tags_1,
	sizeof(asn_DEF_ComputedLane_tags_1)
		/sizeof(asn_DEF_ComputedLane_tags_1[0]), /* 1 */
	asn_DEF_ComputedLane_tags_1,	/* Same as above */
	sizeof(asn_DEF_ComputedLane_tags_1)
		/sizeof(asn_DEF_ComputedLane_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ComputedLane_1,
	7,	/* Elements count */
	&asn_SPC_ComputedLane_specs_1	/* Additional specs */
};

