/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../J2735_R41_Source_mod.ASN"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#include "RTCM-Revision.h"

int
RTCM_Revision_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
RTCM_Revision_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

void
RTCM_Revision_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	RTCM_Revision_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
RTCM_Revision_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	RTCM_Revision_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
RTCM_Revision_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	RTCM_Revision_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
RTCM_Revision_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	RTCM_Revision_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
RTCM_Revision_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	RTCM_Revision_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
RTCM_Revision_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	RTCM_Revision_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

asn_dec_rval_t
RTCM_Revision_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	RTCM_Revision_1_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

asn_enc_rval_t
RTCM_Revision_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	RTCM_Revision_1_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_RTCM_Revision_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  5,  5,  0,  16 }	/* (0..16,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_INTEGER_enum_map_t asn_MAP_RTCM_Revision_value2enum_1[] = {
	{ 0,	7,	"unknown" },
	{ 1,	8,	"reserved" },
	{ 2,	7,	"rtcmCMR" },
	{ 3,	12,	"rtcmCMR-Plus" },
	{ 4,	9,	"rtcmSAPOS" },
	{ 5,	13,	"rtcmSAPOS-Adv" },
	{ 6,	8,	"rtcmRTCA" },
	{ 7,	7,	"rtcmRAW" },
	{ 8,	9,	"rtcmRINEX" },
	{ 9,	7,	"rtcmSP3" },
	{ 10,	9,	"rtcmBINEX" },
	{ 19,	10,	"rtcmRev2-x" },
	{ 20,	10,	"rtcmRev2-0" },
	{ 21,	10,	"rtcmRev2-1" },
	{ 23,	10,	"rtcmRev2-3" },
	{ 30,	10,	"rtcmRev3-0" },
	{ 31,	10,	"rtcmRev3-1" }
	/* This list is extensible */
};
static unsigned int asn_MAP_RTCM_Revision_enum2value_1[] = {
	1,	/* reserved(1) */
	10,	/* rtcmBINEX(10) */
	2,	/* rtcmCMR(2) */
	3,	/* rtcmCMR-Plus(3) */
	7,	/* rtcmRAW(7) */
	8,	/* rtcmRINEX(8) */
	6,	/* rtcmRTCA(6) */
	12,	/* rtcmRev2-0(20) */
	13,	/* rtcmRev2-1(21) */
	14,	/* rtcmRev2-3(23) */
	11,	/* rtcmRev2-x(19) */
	15,	/* rtcmRev3-0(30) */
	16,	/* rtcmRev3-1(31) */
	4,	/* rtcmSAPOS(4) */
	5,	/* rtcmSAPOS-Adv(5) */
	9,	/* rtcmSP3(9) */
	0	/* unknown(0) */
	/* This list is extensible */
};
static asn_INTEGER_specifics_t asn_SPC_RTCM_Revision_specs_1 = {
	asn_MAP_RTCM_Revision_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_RTCM_Revision_enum2value_1,	/* N => "tag"; sorted by N */
	17,	/* Number of elements in the maps */
	18,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_RTCM_Revision_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RTCM_Revision = {
	"RTCM-Revision",
	"RTCM-Revision",
	RTCM_Revision_free,
	RTCM_Revision_print,
	RTCM_Revision_constraint,
	RTCM_Revision_decode_ber,
	RTCM_Revision_encode_der,
	RTCM_Revision_decode_xer,
	RTCM_Revision_encode_xer,
	RTCM_Revision_decode_uper,
	RTCM_Revision_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RTCM_Revision_tags_1,
	sizeof(asn_DEF_RTCM_Revision_tags_1)
		/sizeof(asn_DEF_RTCM_Revision_tags_1[0]), /* 1 */
	asn_DEF_RTCM_Revision_tags_1,	/* Same as above */
	sizeof(asn_DEF_RTCM_Revision_tags_1)
		/sizeof(asn_DEF_RTCM_Revision_tags_1[0]), /* 1 */
	&asn_PER_type_RTCM_Revision_constr_1,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_RTCM_Revision_specs_1	/* Additional specs */
};

