/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_201603.asn1"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#ifndef	_MobilityGUID_H_
#define	_MobilityGUID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IA5String.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MobilityGUID */
typedef IA5String_t	 MobilityGUID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MobilityGUID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MobilityGUID;
asn_struct_free_f MobilityGUID_free;
asn_struct_print_f MobilityGUID_print;
asn_constr_check_f MobilityGUID_constraint;
ber_type_decoder_f MobilityGUID_decode_ber;
der_type_encoder_f MobilityGUID_encode_der;
xer_type_decoder_f MobilityGUID_decode_xer;
xer_type_encoder_f MobilityGUID_encode_xer;
oer_type_decoder_f MobilityGUID_decode_oer;
oer_type_encoder_f MobilityGUID_encode_oer;
per_type_decoder_f MobilityGUID_decode_uper;
per_type_encoder_f MobilityGUID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MobilityGUID_H_ */
#include "asn_internal.h"
