/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SDSM"
 * 	found in "J2735_201603_2023-06-22.asn"
 * 	`asn1c -fcompound-names `
 */

#ifndef	_YawDetected_H_
#define	_YawDetected_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* YawDetected */
typedef long	 YawDetected_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_YawDetected_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_YawDetected;
asn_struct_free_f YawDetected_free;
asn_struct_print_f YawDetected_print;
asn_constr_check_f YawDetected_constraint;
ber_type_decoder_f YawDetected_decode_ber;
der_type_encoder_f YawDetected_encode_der;
xer_type_decoder_f YawDetected_decode_xer;
xer_type_encoder_f YawDetected_encode_xer;
oer_type_decoder_f YawDetected_decode_oer;
oer_type_encoder_f YawDetected_encode_oer;
per_type_decoder_f YawDetected_decode_uper;
per_type_encoder_f YawDetected_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _YawDetected_H_ */
#include <asn_internal.h>
