openapi: 3.0.0
info:
  title: Port Drayage Web Service.
  description: Web Service for Loading/Unloading/Inspection interactions for Port Drayage Operations. 
  version: "1.0"
servers:
  - url: http://127.0.0.1:8080
    description: Unsecured hosting for development
  - url: https://127.0.0.1:8443
    description: Secured hosting for deployment
paths:
  /loading:
    post:
      summary: Request a container is loaded on to freight vehicle.
      description: Provide ContainerRequest JSON to request a container with a given id be loaded on a vehicle with a given id.
      requestBody:
        description: Request contains container ID and Vehicle ID
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContainerRequest'
      responses:
        '201':
          description: Created   
        '400':
          description: Bad Request 
  /loading/pending:
    get:
      summary: List of all pending loading actions.
      description: Provides a list of ContainerActionStatus JSON objects describing the loading actions waiting to be started.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatusList'
  /loading/{vehicle_id}:
     get:
      parameters:
        - in: path
          name: vehicle_id
          schema:
            type: string
          required: true
          description: String static vehicle id 
      summary: Request most recent loading action status for given vehicle.
      description: Returns the most recent loading ContainerActionStatus JSON for a given vehicle, whether pending, current or completed.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContainerActionStatus'
        '400':
          description: Bad Request  
  /unloading:
    post:
      summary: Request a container is unloaded on to freight Vehicle.
      description: Provide ContainerRequest JSON to request a container with a given id be unloaded on a vehicle with a given id.
      requestBody:
        description: Request contains container ID and Vehicle ID
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContainerRequest'
      responses:
        '201':
          description: Created
  /unloading/pending:
    get:
      summary: List of all pending unloading actions and status.
      description: Provides a list of ContainerActionStatus JSON describing the unloading actions waiting to be started.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatusList'    
  /unloading/{vehicle_id}:
     get:
      parameters:
        - in: path
          name: vehicle_id
          schema:
            type: string
          required: true
          description: String static vehicle id
      summary: Request most recent loading action status for given vehicle.
      description: Returns the most recent unloading ContainerActionStatus JSON for a given vehicle, whether pending, current or completed.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContainerActionStatus'
        '400':
          description: Bad Request  
  /inspection:
    post:
      summary: Request a container is inspected on to Freight Vehicle.
      description: Provide InspectionRequest JSON to request a container with a given id be inspected on a vehicle with a given id.
      requestBody:
        description: Request contains container ID and Vehicle ID
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InspectionRequest'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
  /inspection/holding:
    post:
      summary: Request for further inspection at holding area
      description: After being instructed to proceed to holding area and navigating to holding area, vehicle will request further inspection at holding area
      requestBody:
        description: Request contains container ID and Vehicle ID
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InspectionRequest'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
  /inspection/pending:
    get:
      summary: List of all pending inspection actions and status.
      description: Get all inspection actions that have been requested by are not yet in progress.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InspectionStatusList'  
  /inspection/{vehicle_id}:
    get:
      parameters:
        - in: path
          name: vehicle_id
          schema:
            type: string
          required: true
          description: String static vehicle id
      summary: Request most recent inspection status for given vehicle.
      description: Returns the most recent InspectionStatus JSON for a given vehicle, whether pending, current or completed..
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InspectionStatus'
        '400':
          description: Bad Request  
  
components:
  schemas:
    ContainerRequest:
      title: Container Request
      type: object
      properties:
        vehicle_id:
          type: string
          description: ID of vehicle
        container_id:
          type: string
          description: ID of container
      required:
        - vehicle_id
        - container_id
    ContainerActionStatus:
      title: Container Action Status
      type: object
      properties:
        vehicle_id:
          type: string
          description: ID of vehicle
        container_id:
          type: string
          description: ID of container
        status:
          type: string
          enum:
           - REQUESTED
           - LOADING
           - UNLOADING
           - LOADED
           - UNLOADED
           - PENDING
           - ABORTED
        requested:
          type: long
        completed:
          type: long
      required:
        - vehicle_id
        - container_id
        - status
        - started
    ActionStatusList:
      title: List of Container Action Status elements
      type: object
      properties:
        actions:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/ContainerActionStatus'  
    InspectionRequest:
      title: Inspection Request
      type: object
      properties:
        vehicle_id:
          type: string
          description: ID of vehicle
        container_id:
          type: string
          description: ID of container
      required:
        - vehicle_id
        - container_id
    InspectionStatus:
      title: Inspection Status
      type: object
      properties:
        vehicle_id:
          type: string
          description: ID of vehicle
        container_id:
          type: string
          description: ID of container
        status:
          type: string
          enum:
           - PENDING
           - PROCEED_TO_HOLDING
           - PASSED
           - FAILED
           - HOLDING
        requested:
          type: long
        completed:
          type: long
      required:
        - vehicle_id
        - container_id
        - status
    InspectionStatusList:
      title: List of Container Action Status elements
      type: object
      properties:
        inspections:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/InspectionStatus'  