openapi: 3.0.0
info:
  title: Port Drayage Web Service.
  description: Web Service for Loading/Unloading/Inspection interactions for Port Drayage Operations. 
  version: "1.0"
servers:
  - url: http://127.0.0.1:8090
    description: Unsecured hosting for development
  - url: https://127.0.0.1:8443
    description: Secured hosting for deployment
paths:
  /loading:
    post:
      summary: Request a container is loaded on to freight vehicle.
      description:
        Provide ContainerRequest JSON to request a container with a given id be loaded on a vehicle with a given id.\
        Also requires an action id to uniquely identify the requested action. If an action already exists for a given action id\
        request will be discarded as duplicate and result in 400 response.
      requestBody:
        description: Request contains container ID, Vehicle ID and an Action ID
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ContainerRequest"
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
  /loading/pending:
    get:
      summary: List of all pending loading actions.
      description:
        Provides a list of ContainerActionStatus JSON objects describing the loading actions waiting to be started.\
        Any action requested while there is a current action in progress will be added to this list. Actions in this list will\
        replace the current action after it is completed in a first-in first-out order.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActionStatusList"
  /loading/start/{action_id}:
    post:
      parameters:
        - in: path
          name: action_id
          schema:
            type: string
          required: true
          description: ID of action
      summary: Start a loading action.
      description:
        Will attempt to start current loading action. This REST endpoint is only intended for UI form submission. Will\
        be triggered on UI interaction to indicate a loading action has started. Will return 400 if provided action id is not \
        current action.
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
  /loading/complete/{action_id}:
    post:
      parameters:
        - in: path
          name: action_id
          schema:
            type: string
          required: true
          description: ID of action
      summary: Complete a loading action.
      description:
        Will attempt to complete current loading action. This REST endpoint is only intended for UI form submission. Will\
        be triggered on UI interaction to indicate a loading action has been completed. Will return 400 if provided action id is not\
        current action.
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
  /loading/{action_id}:
    get:
      parameters:
        - in: path
          name: action_id
          schema:
            type: string
          required: true
          description: ID of action
      summary: Returns action with given ID
      description: Returns action with given ID. If none is found returns 400. Intended for polling the status of a request action.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContainerActionStatus"
        "400":
          description: Bad Request
  /unloading:
    post:
      summary: Request a container is unloaded on to freight Vehicle.
      description:
        Provide ContainerRequest JSON to request a container with a given id be unloaded on a vehicle with a given id.\
        Also requires an action id to uniquely identify the requested action. If an action already exists for a given action id\
        request will be discarded as duplicate and result in 400 response.
      requestBody:
        description: Request contains container ID, Vehicle ID and an Action ID
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ContainerRequest"
      responses:
        "201":
          description: Created
  /unloading/pending:
    get:
      summary: List of all pending unloading actions and status.
      description:
        Provides a list of ContainerActionStatus JSON describing the unloading actions waiting to be started.\
        Any action requested while there is a current action in progress will be added to this list. Actions in this list will\
        replace the current action after it is completed in a first-in first-out order.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActionStatusList"
  /unloading/start/{action_id}:
    post:
      parameters:
        - in: path
          name: action_id
          schema:
            type: string
          required: true
          description: ID of action
      summary: Start an unloading action.
      description:
        Will attempt to start current unloading action. This REST endpoint is only intended for UI form submission. Will\
        be triggered on UI interaction to indicate a unloading action has started. Will return 400 if provided action id is not current\
        action.
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
  /unloading/complete/{action_id}:
    post:
      parameters:
        - in: path
          name: action_id
          schema:
            type: string
          required: true
          description: ID of action
      summary: Complete an unloading action.
      description:
        Will attempt to complete current unloading action. This REST endpoint is only intended for UI form submission. Will\
        be triggered on UI interaction to indicate an unloading action has been completed. Will return 400 if provided action id is not\
        current action.
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
  /unloading/{action_id}:
    get:
      parameters:
        - in: path
          name: action_id
          schema:
            type: string
          required: true
          description: ID of action
      summary: Returns action with given ID
      description: Returns action with given ID. If none is found returns 400. Intended for polling the status of a request action.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContainerActionStatus"
        "400":
          description: Bad Request
  /inspection:
    post:
      summary: Request a container is inspected on to Freight Vehicle.
      description:
        Provide InspectionRequest JSON to request a container with a given id be inspected on a vehicle with a given id.\
        Also requires an action id to uniquely identify the requested action. If an action already exists for a given action id\
        request will be discarded as duplicate and result in 400 response.
      requestBody:
        description: Request contains container ID and Vehicle ID
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InspectionRequest"
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
  /inspection/holding/{action_id}:
    post:
      parameters:
        - in: path
          name: action_id
          schema:
            type: string
          required: true
          description: ID of action
      summary: Vehicle has arrive at Holding area an is waiting on inspection.
      description:
        After being instructed to proceed to holding area and navigating to holding area, vehicle will request further inspection at holding\
        area. This request will be sent from the PortDrayage V2X-Hub Plugin after receiving a vehicles arrival message at the holding area.\
        Will return 400 if not current action or status is not PROCEED_TO_HOLDING and discard request.
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
  /inspection/pending:
    get:
      summary: List of all pending inspection actions and status.
      description:
        Provides a list of InspectionStatus JSON objects describing the inspection actions waiting to be started.\
        Any action requested while there is a current action in progress will be added to this list. Actions in this list will\
        replace the current action after it is completed in a first-in first-out order.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionStatusList"
  /inspection/complete/{action_id}:
    post:
      parameters:
        - in: path
          name: action_id
          schema:
            type: string
          required: true
          description: ID of action
      summary: Complete an inspection action.
      description:
        Will attempt to complete current inspection. This REST endpoint is only intended for UI form submission. Will\
        be triggered on UI interaction to indicate an inspection has been completed. Will return 400 if provided action id is not\
        current action.
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
  /inspection/hold/{action_id}:
    post:
      parameters:
        - in: path
          name: action_id
          schema:
            type: string
          required: true
          description: ID of action
      summary: Request vehicle proceed to holding area for further inspection
      description: Will attempt to request vehicle proceed to holding area for further inspection. Will return 400 if no current action
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
  /inspection/{action_id}:
    get:
      parameters:
        - in: path
          name: action_id
          schema:
            type: string
          required: true
          description: ID of action
      summary: Returns action with given ID
      description: Returns action with given ID. If non is found returns 400. Intended for polling inspection status.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionStatus"
        "400":
          description: Bad Request
components:
  schemas:
    ContainerRequest:
      title: Container Request
      type: object
      properties:
        vehicle_id:
          type: string
          description: ID of vehicle
        container_id:
          type: string
          description: ID of container
        action_id:
          type: string
          description: ID of action
      required:
        - vehicle_id
        - container_id
        - action_id
    ContainerActionStatus:
      title: Container Action Status
      type: object
      properties:
        vehicle_id:
          type: string
          description: ID of vehicle
        container_id:
          type: string
          description: ID of container
        action_id:
          type: string
          description: ID of action
        status:
          type: string
          enum:
            - LOADING
            - UNLOADING
            - LOADED
            - UNLOADED
            - PENDING
            - ABORTED
        requested:
          type: integer
          format: int64
        completed:
          type: integer
          format: int64
      required:
        - vehicle_id
        - container_id
        - action_id
        - status
        - requested
    ActionStatusList:
      title: List of Container Action Status elements
      type: object
      properties:
        actions:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/ContainerActionStatus"
    InspectionRequest:
      title: Inspection Request
      type: object
      properties:
        vehicle_id:
          type: string
          description: ID of vehicle
        container_id:
          type: string
          description: ID of container
        action_id:
          type: string
          description: ID of action
      required:
        - vehicle_id
        - container_id
        - action_id
    InspectionStatus:
      title: Inspection Status
      type: object
      properties:
        vehicle_id:
          type: string
          description: ID of vehicle
        container_id:
          type: string
          description: ID of container
        action_id:
          type: string
          description: ID of action
        status:
          type: string
          enum:
            - PENDING
            - PROCEED_TO_HOLDING
            - PASSED
            - FAILED
            - HOLDING
        requested:
          type: integer
          format: int64
        completed:
          type: integer
          format: int64
      required:
        - vehicle_id
        - container_id
        - action_id
        - status
        - requested
    InspectionStatusList:
      title: List of Container Action Status elements
      type: object
      properties:
        inspections:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/InspectionStatus"
