/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_201603_ASN_CC.asn"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted -fskeletons-copy`
 */

#ifndef	_PathNode_H_
#define	_PathNode_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PathNode */
typedef struct PathNode {
	long	 x;
	long	 y;
	long	*z;	/* OPTIONAL */
	long	*width;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathNode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathNode;
extern asn_SEQUENCE_specifics_t asn_SPC_PathNode_specs_1;
extern asn_TYPE_member_t asn_MBR_PathNode_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _PathNode_H_ */
#include "asn_internal.h"
