/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_201603_2023-06-22.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted`
 */

#ifndef	_TestMessage07_H_
#define	_TestMessage07_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MobilityHeader.h"
#include "EmergencyVehicleAck.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TestMessage07 */
typedef struct TestMessage07 {
	MobilityHeader_t	 header;
	EmergencyVehicleAck_t	 body;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestMessage07_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestMessage07;
extern asn_SEQUENCE_specifics_t asn_SPC_TestMessage07_specs_1;
extern asn_TYPE_member_t asn_MBR_TestMessage07_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TestMessage07_H_ */
#include "asn_internal.h"
