
/**
 * WARNING: DO NOT EDIT THIS FILE
 *
 * This source file was generated from the CPlusPlusGenerator.xsl stylesheet
 *
 * Your changes will be overwritten when this tool executes again.  In order
 * to edit the contents, you must go into the source XML files
 *
 * @author Greg Baumgardner
 */
 

#ifndef INCLUDE_TMXERROR_H_
#define INCLUDE_TMXERROR_H_

#ifndef CONSTEXPR
#if __cplusplus > 199711L
#define CONSTEXPR constexpr
#else
#ifdef __GNUC__
#define CONSTEXPR __attribute__ ((unused))
#else
#define CONSTEXPR
#endif
#endif
#endif

		
	
namespace tmx {
		
namespace messages {
			
			
enum TmxErrorNumber 
{
		None = 0,
		ManifestLoad = 1,
		ManifestParse = 2,
		ManifestExtract = 3,
		PluginNoName = 4,
		ConfigFormat = 5,
		ConfigDuplicateKey = 6,
		ConfigMissingKey = 7,
		ConfigMissingDefault = 8,
		ConnectFail = 9,
		ConnectionDropped = 10,
		ConfigKeyDoesntExist = 11,
		MessageParse = 12,
		Assert = 13,
		MsgTypeCollectionFormat = 14,
		MsgTypeCollectionMissingType = 15,
		MsgTypeCollectionMissingSubType = 16,
		MsgTypeCollectionDuplicate = 17
};
		
		
static CONSTEXPR const char *TMXERRORNUMBER_NONE_STRING = "None";
static CONSTEXPR const char *TMXERRORNUMBER_MANIFESTLOAD_STRING = "ManifestLoad";
static CONSTEXPR const char *TMXERRORNUMBER_MANIFESTPARSE_STRING = "ManifestParse";
static CONSTEXPR const char *TMXERRORNUMBER_MANIFESTEXTRACT_STRING = "ManifestExtract";
static CONSTEXPR const char *TMXERRORNUMBER_PLUGINNONAME_STRING = "PluginNoName";
static CONSTEXPR const char *TMXERRORNUMBER_CONFIGFORMAT_STRING = "ConfigFormat";
static CONSTEXPR const char *TMXERRORNUMBER_CONFIGDUPLICATEKEY_STRING = "ConfigDuplicateKey";
static CONSTEXPR const char *TMXERRORNUMBER_CONFIGMISSINGKEY_STRING = "ConfigMissingKey";
static CONSTEXPR const char *TMXERRORNUMBER_CONFIGMISSINGDEFAULT_STRING = "ConfigMissingDefault";
static CONSTEXPR const char *TMXERRORNUMBER_CONNECTFAIL_STRING = "ConnectFail";
static CONSTEXPR const char *TMXERRORNUMBER_CONNECTIONDROPPED_STRING = "ConnectionDropped";
static CONSTEXPR const char *TMXERRORNUMBER_CONFIGKEYDOESNTEXIST_STRING = "ConfigKeyDoesntExist";
static CONSTEXPR const char *TMXERRORNUMBER_MESSAGEPARSE_STRING = "MessageParse";
static CONSTEXPR const char *TMXERRORNUMBER_ASSERT_STRING = "Assert";
static CONSTEXPR const char *TMXERRORNUMBER_MSGTYPECOLLECTIONFORMAT_STRING = "MsgTypeCollectionFormat";
static CONSTEXPR const char *TMXERRORNUMBER_MSGTYPECOLLECTIONMISSINGTYPE_STRING = "MsgTypeCollectionMissingType";
static CONSTEXPR const char *TMXERRORNUMBER_MSGTYPECOLLECTIONMISSINGSUBTYPE_STRING = "MsgTypeCollectionMissingSubType";
static CONSTEXPR const char *TMXERRORNUMBER_MSGTYPECOLLECTIONDUPLICATE_STRING = "MsgTypeCollectionDuplicate";
		
} /* End namespace messages */
	
} /* End namespace tmx */

		
#endif /* INCLUDE_TMXERROR_H_ */
	