/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "ISO17573-EfcDataDictionary.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_AxleWeightLimits_H_
#define	_AxleWeightLimits_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Int2Unsigned.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AxleWeightLimits */
typedef struct AxleWeightLimits {
	Int2Unsigned_t	 maxLadenweightOnAxle1;
	Int2Unsigned_t	 maxLadenweightOnAxle2;
	Int2Unsigned_t	 maxLadenweightOnAxle3;
	Int2Unsigned_t	 maxLadenweightOnAxle4;
	Int2Unsigned_t	 maxLadenweightOnAxle5;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AxleWeightLimits_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AxleWeightLimits;
extern asn_SEQUENCE_specifics_t asn_SPC_AxleWeightLimits_specs_1;
extern asn_TYPE_member_t asn_MBR_AxleWeightLimits_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _AxleWeightLimits_H_ */
#include "asn_internal.h"
