/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RoadSafetyMessage"
 * 	found in "J2945-4-RoadSafetyMessage-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_BankAngle_H_
#define	_BankAngle_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* BankAngle */
typedef long	 BankAngle_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BankAngle_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BankAngle;
asn_struct_free_f BankAngle_free;
asn_struct_print_f BankAngle_print;
asn_constr_check_f BankAngle_constraint;
ber_type_decoder_f BankAngle_decode_ber;
der_type_encoder_f BankAngle_encode_der;
xer_type_decoder_f BankAngle_decode_xer;
xer_type_encoder_f BankAngle_encode_xer;
oer_type_decoder_f BankAngle_decode_oer;
oer_type_encoder_f BankAngle_encode_oer;
per_type_decoder_f BankAngle_decode_uper;
per_type_encoder_f BankAngle_encode_uper;
per_type_decoder_f BankAngle_decode_aper;
per_type_encoder_f BankAngle_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _BankAngle_H_ */
#include "asn_internal.h"
