/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RoadSafetyMessage"
 * 	found in "J2945-4-RoadSafetyMessage-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_CurveContainer_H_
#define	_CurveContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SpeedAdvice.h"
#include "Radius.h"
#include "BankAngle.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FrictionInformation;
struct RegionInfo;

/* CurveContainer */
typedef struct CurveContainer {
	SpeedAdvice_t	 advisorySpeed;
	struct FrictionInformation	*surfaceCondition;	/* OPTIONAL */
	Radius_t	*minRadius;	/* OPTIONAL */
	BankAngle_t	*bankAngle;	/* OPTIONAL */
	struct RegionInfo	*curveRegion;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CurveContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CurveContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_CurveContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_CurveContainer_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FrictionInformation.h"
#include "RegionInfo.h"

#endif	/* _CurveContainer_H_ */
#include "asn_internal.h"
