/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "BasicSafetyMessage"
 * 	found in "J2735-BasicSafetyMessage-2024-rel-v1.1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_DisabledVehicle_H_
#define	_DisabledVehicle_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ITIS_ITIScodes.h"
#include "ITIS_GenericLocations.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DisabledVehicle */
typedef struct DisabledVehicle {
	ITIS_ITIScodes_t	 statusDetails;
	ITIS_GenericLocations_t	*locationDetails;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DisabledVehicle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DisabledVehicle;
extern asn_SEQUENCE_specifics_t asn_SPC_DisabledVehicle_specs_1;
extern asn_TYPE_member_t asn_MBR_DisabledVehicle_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DisabledVehicle_H_ */
#include "asn_internal.h"
