/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "ISO17573-EfcDataDictionary.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_EmissionUnit_H_
#define	_EmissionUnit_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EmissionUnit {
	EmissionUnit_mgPerKm	= 0,
	EmissionUnit_mgPerKwh	= 1
} e_EmissionUnit;

/* EmissionUnit */
typedef long	 EmissionUnit_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EmissionUnit_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EmissionUnit;
asn_struct_free_f EmissionUnit_free;
asn_struct_print_f EmissionUnit_print;
asn_constr_check_f EmissionUnit_constraint;
ber_type_decoder_f EmissionUnit_decode_ber;
der_type_encoder_f EmissionUnit_encode_der;
xer_type_decoder_f EmissionUnit_decode_xer;
xer_type_encoder_f EmissionUnit_encode_xer;
oer_type_decoder_f EmissionUnit_decode_oer;
oer_type_encoder_f EmissionUnit_encode_oer;
per_type_decoder_f EmissionUnit_decode_uper;
per_type_encoder_f EmissionUnit_encode_uper;
per_type_decoder_f EmissionUnit_decode_aper;
per_type_encoder_f EmissionUnit_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EmissionUnit_H_ */
#include "asn_internal.h"
