/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "ISO17573-EfcDataDictionary.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_EquipmentObuId_H_
#define	_EquipmentObuId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EquipmentObuId */
typedef OCTET_STRING_t	 EquipmentObuId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EquipmentObuId;
asn_struct_free_f EquipmentObuId_free;
asn_struct_print_f EquipmentObuId_print;
asn_constr_check_f EquipmentObuId_constraint;
ber_type_decoder_f EquipmentObuId_decode_ber;
der_type_encoder_f EquipmentObuId_encode_der;
xer_type_decoder_f EquipmentObuId_decode_xer;
xer_type_encoder_f EquipmentObuId_encode_xer;
oer_type_decoder_f EquipmentObuId_decode_oer;
oer_type_encoder_f EquipmentObuId_encode_oer;
per_type_decoder_f EquipmentObuId_decode_uper;
per_type_encoder_f EquipmentObuId_encode_uper;
per_type_decoder_f EquipmentObuId_decode_aper;
per_type_encoder_f EquipmentObuId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EquipmentObuId_H_ */
#include "asn_internal.h"
