/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RoadUserChargingReportMessage"
 * 	found in "J3217-R-RoadUserChargingReportMsg-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_ItemizedChargerData_H_
#define	_ItemizedChargerData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OBJECT_IDENTIFIER.h"
#include "DescriptiveName.h"
#include "NativeInteger.h"
#include "PaymentFee.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TripInfo;

/* ItemizedChargerData */
typedef struct ItemizedChargerData {
	OBJECT_IDENTIFIER_t	 chargerID;
	DescriptiveName_t	*chargingDescription;	/* OPTIONAL */
	long	*configID;	/* OPTIONAL */
	struct TripInfo	*tripInfo;	/* OPTIONAL */
	PaymentFee_t	 totalPaidToCharger;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ItemizedChargerData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ItemizedChargerData;
extern asn_SEQUENCE_specifics_t asn_SPC_ItemizedChargerData_specs_1;
extern asn_TYPE_member_t asn_MBR_ItemizedChargerData_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TripInfo.h"

#endif	/* _ItemizedChargerData_H_ */
#include "asn_internal.h"
