/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "J2540-2-J2540ITIS-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_J2540ITIS_GenericLocations_H_
#define	_J2540ITIS_GenericLocations_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum J2540ITIS_GenericLocations {
	J2540ITIS_GenericLocations_on_bridges	= 7937,
	J2540ITIS_GenericLocations_in_tunnels	= 7938,
	J2540ITIS_GenericLocations_entering_or_leaving_tunnels	= 7939,
	J2540ITIS_GenericLocations_on_ramps	= 7940,
	J2540ITIS_GenericLocations_in_road_construction_area	= 7941,
	J2540ITIS_GenericLocations_around_a_curve	= 7942,
	J2540ITIS_GenericLocations_on_curve	= 8026,
	J2540ITIS_GenericLocations_on_tracks	= 8009,
	J2540ITIS_GenericLocations_in_street	= 8025,
	J2540ITIS_GenericLocations_shoulder	= 8027,
	J2540ITIS_GenericLocations_on_minor_roads	= 7943,
	J2540ITIS_GenericLocations_in_the_opposing_lanes	= 7944,
	J2540ITIS_GenericLocations_adjacent_to_roadway	= 7945,
	J2540ITIS_GenericLocations_across_tracks	= 8024,
	J2540ITIS_GenericLocations_on_bend	= 7946,
	J2540ITIS_GenericLocations_intersection	= 8032,
	J2540ITIS_GenericLocations_entire_intersection	= 7947,
	J2540ITIS_GenericLocations_in_the_median	= 7948,
	J2540ITIS_GenericLocations_moved_to_side_of_road	= 7949,
	J2540ITIS_GenericLocations_moved_to_shoulder	= 7950,
	J2540ITIS_GenericLocations_on_the_roadway	= 7951,
	J2540ITIS_GenericLocations_dip	= 8010,
	J2540ITIS_GenericLocations_traffic_circle	= 8011,
	J2540ITIS_GenericLocations_crossover	= 8028,
	J2540ITIS_GenericLocations_cross_road	= 8029,
	J2540ITIS_GenericLocations_side_road	= 8030,
	J2540ITIS_GenericLocations_to	= 8014,
	J2540ITIS_GenericLocations_by	= 8015,
	J2540ITIS_GenericLocations_through	= 8016,
	J2540ITIS_GenericLocations_area_of	= 8017,
	J2540ITIS_GenericLocations_under	= 8018,
	J2540ITIS_GenericLocations_over	= 8019,
	J2540ITIS_GenericLocations_from	= 8020,
	J2540ITIS_GenericLocations_approaching	= 8021,
	J2540ITIS_GenericLocations_entering_at	= 8022,
	J2540ITIS_GenericLocations_exiting_at	= 8023,
	J2540ITIS_GenericLocations_in_shaded_areas	= 7952,
	J2540ITIS_GenericLocations_in_low_lying_areas	= 7953,
	J2540ITIS_GenericLocations_in_the_downtown_area	= 7954,
	J2540ITIS_GenericLocations_in_the_inner_city_area	= 7955,
	J2540ITIS_GenericLocations_in_parts	= 7956,
	J2540ITIS_GenericLocations_in_some_places	= 7957,
	J2540ITIS_GenericLocations_in_the_ditch	= 7958,
	J2540ITIS_GenericLocations_in_the_valley	= 7959,
	J2540ITIS_GenericLocations_on_hill_top	= 7960,
	J2540ITIS_GenericLocations_near_the_foothills	= 7961,
	J2540ITIS_GenericLocations_at_high_altitudes	= 7962,
	J2540ITIS_GenericLocations_near_the_lake	= 7963,
	J2540ITIS_GenericLocations_near_the_shore	= 7964,
	J2540ITIS_GenericLocations_nearby_basin	= 8008,
	J2540ITIS_GenericLocations_over_the_crest_of_a_hill	= 7965,
	J2540ITIS_GenericLocations_other_than_on_the_roadway	= 7966,
	J2540ITIS_GenericLocations_near_the_beach	= 7967,
	J2540ITIS_GenericLocations_near_beach_access_point	= 7968,
	J2540ITIS_GenericLocations_mountain_pass	= 8006,
	J2540ITIS_GenericLocations_lower_level	= 7969,
	J2540ITIS_GenericLocations_upper_level	= 7970,
	J2540ITIS_GenericLocations_coast	= 8034,
	J2540ITIS_GenericLocations_airport	= 7971,
	J2540ITIS_GenericLocations_concourse	= 7972,
	J2540ITIS_GenericLocations_gate	= 7973,
	J2540ITIS_GenericLocations_baggage_claim	= 7974,
	J2540ITIS_GenericLocations_customs_point	= 7975,
	J2540ITIS_GenericLocations_reservation_center	= 8007,
	J2540ITIS_GenericLocations_station	= 7976,
	J2540ITIS_GenericLocations_platform	= 7977,
	J2540ITIS_GenericLocations_dock	= 7978,
	J2540ITIS_GenericLocations_depot	= 7979,
	J2540ITIS_GenericLocations_ev_charging_point	= 7980,
	J2540ITIS_GenericLocations_information_welcome_point	= 7981,
	J2540ITIS_GenericLocations_at_rest_area	= 7982,
	J2540ITIS_GenericLocations_at_service_area	= 7983,
	J2540ITIS_GenericLocations_at_weigh_station	= 7984,
	J2540ITIS_GenericLocations_roadside_park	= 8033,
	J2540ITIS_GenericLocations_picnic_areas	= 7985,
	J2540ITIS_GenericLocations_rest_area	= 7986,
	J2540ITIS_GenericLocations_service_stations	= 7987,
	J2540ITIS_GenericLocations_toilets	= 7988,
	J2540ITIS_GenericLocations_bus_stop	= 8031,
	J2540ITIS_GenericLocations_park_and_ride_lot	= 8012,
	J2540ITIS_GenericLocations_on_the_right	= 7989,
	J2540ITIS_GenericLocations_on_the_left	= 7990,
	J2540ITIS_GenericLocations_in_the_center	= 7991,
	J2540ITIS_GenericLocations_in_the_opposite_direction	= 7992,
	J2540ITIS_GenericLocations_cross_traffic	= 7993,
	J2540ITIS_GenericLocations_northbound_traffic	= 7994,
	J2540ITIS_GenericLocations_eastbound_traffic	= 7995,
	J2540ITIS_GenericLocations_southbound_traffic	= 7996,
	J2540ITIS_GenericLocations_westbound_traffic	= 7997,
	J2540ITIS_GenericLocations_north	= 7998,
	J2540ITIS_GenericLocations_south	= 7999,
	J2540ITIS_GenericLocations_east	= 8000,
	J2540ITIS_GenericLocations_west	= 8001,
	J2540ITIS_GenericLocations_northeast	= 8002,
	J2540ITIS_GenericLocations_northwest	= 8003,
	J2540ITIS_GenericLocations_southeast	= 8004,
	J2540ITIS_GenericLocations_southwest	= 8005
} e_J2540ITIS_GenericLocations;

/* J2540ITIS_GenericLocations */
typedef long	 J2540ITIS_GenericLocations_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_J2540ITIS_GenericLocations;
asn_struct_free_f J2540ITIS_GenericLocations_free;
asn_struct_print_f J2540ITIS_GenericLocations_print;
asn_constr_check_f J2540ITIS_GenericLocations_constraint;
ber_type_decoder_f J2540ITIS_GenericLocations_decode_ber;
der_type_encoder_f J2540ITIS_GenericLocations_encode_der;
xer_type_decoder_f J2540ITIS_GenericLocations_decode_xer;
xer_type_encoder_f J2540ITIS_GenericLocations_encode_xer;
oer_type_decoder_f J2540ITIS_GenericLocations_decode_oer;
oer_type_encoder_f J2540ITIS_GenericLocations_encode_oer;
per_type_decoder_f J2540ITIS_GenericLocations_decode_uper;
per_type_encoder_f J2540ITIS_GenericLocations_encode_uper;
per_type_decoder_f J2540ITIS_GenericLocations_decode_aper;
per_type_encoder_f J2540ITIS_GenericLocations_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _J2540ITIS_GenericLocations_H_ */
#include "asn_internal.h"
