/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CooperativeControlMessage"
 * 	found in "J2945-6-CooperativeControlMessage-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_LongitudinalControlState_H_
#define	_LongitudinalControlState_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LongitudinalControlState {
	LongitudinalControlState_unavailable	= 0,
	LongitudinalControlState_manual	= 1,
	LongitudinalControlState_cc	= 2,
	LongitudinalControlState_acc	= 3,
	LongitudinalControlState_caccOne	= 4,
	LongitudinalControlState_caccMultiple	= 5,
	LongitudinalControlState_sensorAuto	= 6,
	LongitudinalControlState_fusedAuto	= 7,
	LongitudinalControlState_manualOver	= 8
	/*
	 * Enumeration is extensible
	 */
} e_LongitudinalControlState;

/* LongitudinalControlState */
typedef long	 LongitudinalControlState_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LongitudinalControlState_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LongitudinalControlState;
extern const asn_INTEGER_specifics_t asn_SPC_LongitudinalControlState_specs_1;
asn_struct_free_f LongitudinalControlState_free;
asn_struct_print_f LongitudinalControlState_print;
asn_constr_check_f LongitudinalControlState_constraint;
ber_type_decoder_f LongitudinalControlState_decode_ber;
der_type_encoder_f LongitudinalControlState_encode_der;
xer_type_decoder_f LongitudinalControlState_decode_xer;
xer_type_encoder_f LongitudinalControlState_encode_xer;
oer_type_decoder_f LongitudinalControlState_decode_oer;
oer_type_encoder_f LongitudinalControlState_encode_oer;
per_type_decoder_f LongitudinalControlState_decode_uper;
per_type_encoder_f LongitudinalControlState_encode_uper;
per_type_decoder_f LongitudinalControlState_decode_aper;
per_type_encoder_f LongitudinalControlState_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LongitudinalControlState_H_ */
#include "asn_internal.h"
