/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "ISO17573-EfcDataDictionary.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_Lpn_H_
#define	_Lpn_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CountryCode.h"
#include "NativeEnumerated.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Lpn__alphabetIndicator {
	Lpn__alphabetIndicator_latinAlphabetNo1	= 1,
	Lpn__alphabetIndicator_latinAlphabetNo2	= 2,
	Lpn__alphabetIndicator_latinAlphabetNo3	= 3,
	Lpn__alphabetIndicator_latinAlphabetNo4	= 4,
	Lpn__alphabetIndicator_latinCyrillicAlphabet	= 5,
	Lpn__alphabetIndicator_latinArabicAlphabet	= 6,
	Lpn__alphabetIndicator_latinGreekAlphabet	= 7,
	Lpn__alphabetIndicator_latinHebrewAlphabet	= 8,
	Lpn__alphabetIndicator_latinAlphabetNo5	= 9,
	Lpn__alphabetIndicator_latinAlphabetNo6	= 10,
	Lpn__alphabetIndicator_twoOctetBMP	= 11,
	Lpn__alphabetIndicator_fourOctetCanonical	= 12,
	Lpn__alphabetIndicator_reservedForUse1	= 13,
	Lpn__alphabetIndicator_reservedForUse2	= 14,
	Lpn__alphabetIndicator_reservedForUse3	= 15,
	Lpn__alphabetIndicator_reservedForUse4	= 16,
	Lpn__alphabetIndicator_reservedForUse5	= 17,
	Lpn__alphabetIndicator_reservedForUse6	= 18,
	Lpn__alphabetIndicator_reservedForUse7	= 19,
	Lpn__alphabetIndicator_reservedForUse8	= 20,
	Lpn__alphabetIndicator_reservedForUse9	= 21,
	Lpn__alphabetIndicator_reservedForUse10	= 22,
	Lpn__alphabetIndicator_reservedForUse11	= 23,
	Lpn__alphabetIndicator_reservedForUse12	= 24,
	Lpn__alphabetIndicator_reservedForUse13	= 25,
	Lpn__alphabetIndicator_reservedForUse14	= 26,
	Lpn__alphabetIndicator_reservedForUse15	= 27,
	Lpn__alphabetIndicator_reservedForUse16	= 28,
	Lpn__alphabetIndicator_reservedForUse17	= 29,
	Lpn__alphabetIndicator_reservedForUse18	= 30,
	Lpn__alphabetIndicator_reservedForUse19	= 31,
	Lpn__alphabetIndicator_reservedForUse20	= 32,
	Lpn__alphabetIndicator_reservedForUse21	= 33
} e_Lpn__alphabetIndicator;

/* Lpn */
typedef struct Lpn {
	CountryCode_t	 countryCode;
	long	 alphabetIndicator;
	OCTET_STRING_t	 licencePlateNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Lpn_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_alphabetIndicator_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Lpn;
extern asn_SEQUENCE_specifics_t asn_SPC_Lpn_specs_1;
extern asn_TYPE_member_t asn_MBR_Lpn_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Lpn_H_ */
#include "asn_internal.h"
