/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeDataReport"
 * 	found in "J2945-C-ProbeDataReport-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_RptAveragedRecord_H_
#define	_RptAveragedRecord_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Speed.h"
#include "StdDev.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RptEmissions;

/* RptAveragedRecord */
typedef struct RptAveragedRecord {
	Speed_t	*avgSpeed;	/* OPTIONAL */
	StdDev_t	*speedStdDev;	/* OPTIONAL */
	long	*avgStopDuration;	/* OPTIONAL */
	StdDev_t	*avgStopStdDev;	/* OPTIONAL */
	long	*avgFuelConsumption;	/* OPTIONAL */
	struct RptEmissions	*avgEmissions;	/* OPTIONAL */
	long	*avgNumOfOccupants;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RptAveragedRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RptAveragedRecord;
extern asn_SEQUENCE_specifics_t asn_SPC_RptAveragedRecord_specs_1;
extern asn_TYPE_member_t asn_MBR_RptAveragedRecord_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RptEmissions.h"

#endif	/* _RptAveragedRecord_H_ */
#include "asn_internal.h"
