/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SensorDataSharingMessage"
 * 	found in "J3224-SensorDataSharingMessage-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_SensorDataSharingMessage_PitchRate_H_
#define	_SensorDataSharingMessage_PitchRate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SensorDataSharingMessage_PitchRate */
typedef long	 SensorDataSharingMessage_PitchRate_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SensorDataSharingMessage_PitchRate_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SensorDataSharingMessage_PitchRate;
asn_struct_free_f SensorDataSharingMessage_PitchRate_free;
asn_struct_print_f SensorDataSharingMessage_PitchRate_print;
asn_constr_check_f SensorDataSharingMessage_PitchRate_constraint;
ber_type_decoder_f SensorDataSharingMessage_PitchRate_decode_ber;
der_type_encoder_f SensorDataSharingMessage_PitchRate_encode_der;
xer_type_decoder_f SensorDataSharingMessage_PitchRate_decode_xer;
xer_type_encoder_f SensorDataSharingMessage_PitchRate_encode_xer;
oer_type_decoder_f SensorDataSharingMessage_PitchRate_decode_oer;
oer_type_encoder_f SensorDataSharingMessage_PitchRate_encode_oer;
per_type_decoder_f SensorDataSharingMessage_PitchRate_decode_uper;
per_type_encoder_f SensorDataSharingMessage_PitchRate_encode_uper;
per_type_decoder_f SensorDataSharingMessage_PitchRate_decode_aper;
per_type_encoder_f SensorDataSharingMessage_PitchRate_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SensorDataSharingMessage_PitchRate_H_ */
#include "asn_internal.h"
