/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SignalControlAndPrioritizationRequest"
 * 	found in "J2735-SCPR-2024-ph-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_SignalControlAndPrioritizationRequest_H_
#define	_SignalControlAndPrioritizationRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SignalControlAndPrioritizationRequest */
typedef NULL_t	 SignalControlAndPrioritizationRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalControlAndPrioritizationRequest;
asn_struct_free_f SignalControlAndPrioritizationRequest_free;
asn_struct_print_f SignalControlAndPrioritizationRequest_print;
asn_constr_check_f SignalControlAndPrioritizationRequest_constraint;
ber_type_decoder_f SignalControlAndPrioritizationRequest_decode_ber;
der_type_encoder_f SignalControlAndPrioritizationRequest_encode_der;
xer_type_decoder_f SignalControlAndPrioritizationRequest_decode_xer;
xer_type_encoder_f SignalControlAndPrioritizationRequest_encode_xer;
oer_type_decoder_f SignalControlAndPrioritizationRequest_decode_oer;
oer_type_encoder_f SignalControlAndPrioritizationRequest_encode_oer;
per_type_decoder_f SignalControlAndPrioritizationRequest_decode_uper;
per_type_encoder_f SignalControlAndPrioritizationRequest_encode_uper;
per_type_decoder_f SignalControlAndPrioritizationRequest_decode_aper;
per_type_encoder_f SignalControlAndPrioritizationRequest_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalControlAndPrioritizationRequest_H_ */
#include "asn_internal.h"
