/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "J2540-2-J2540ITIS-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_StatesAndTerritories_H_
#define	_StatesAndTerritories_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StatesAndTerritories {
	StatesAndTerritories_alabama	= 12801,
	StatesAndTerritories_alaska	= 12802,
	StatesAndTerritories_american_Samoa	= 12803,
	StatesAndTerritories_arizona	= 12804,
	StatesAndTerritories_arkansas	= 12805,
	StatesAndTerritories_california	= 12806,
	StatesAndTerritories_colorado	= 12807,
	StatesAndTerritories_connecticut	= 12808,
	StatesAndTerritories_delaware	= 12809,
	StatesAndTerritories_district_of_Columbia	= 12810,
	StatesAndTerritories_florida	= 12811,
	StatesAndTerritories_georgia	= 12812,
	StatesAndTerritories_guam	= 12813,
	StatesAndTerritories_hawaii	= 12814,
	StatesAndTerritories_idaho	= 12815,
	StatesAndTerritories_illinois	= 12816,
	StatesAndTerritories_indiana	= 12817,
	StatesAndTerritories_iowa	= 12818,
	StatesAndTerritories_kansas	= 12819,
	StatesAndTerritories_kentucky	= 12820,
	StatesAndTerritories_louisiana	= 12821,
	StatesAndTerritories_maine	= 12822,
	StatesAndTerritories_maryland	= 12823,
	StatesAndTerritories_massachusetts	= 12824,
	StatesAndTerritories_michigan	= 12825,
	StatesAndTerritories_minnesota	= 12826,
	StatesAndTerritories_mississippi	= 12827,
	StatesAndTerritories_missouri	= 12828,
	StatesAndTerritories_montana	= 12829,
	StatesAndTerritories_nebraska	= 12830,
	StatesAndTerritories_nevada	= 12831,
	StatesAndTerritories_new_Hampshire	= 12832,
	StatesAndTerritories_new_Jersey	= 12833,
	StatesAndTerritories_new_Mexico	= 12834,
	StatesAndTerritories_new_York	= 12835,
	StatesAndTerritories_north_Carolina	= 12836,
	StatesAndTerritories_north_Dakota	= 12837,
	StatesAndTerritories_northern_Marianas_Islands	= 12838,
	StatesAndTerritories_ohio	= 12839,
	StatesAndTerritories_oklahoma	= 12840,
	StatesAndTerritories_oregon	= 12841,
	StatesAndTerritories_pennsylvania	= 12842,
	StatesAndTerritories_puerto_rico	= 12843,
	StatesAndTerritories_rhode_Island	= 12844,
	StatesAndTerritories_south_Carolina	= 12845,
	StatesAndTerritories_south_Dakota	= 12846,
	StatesAndTerritories_tennessee	= 12847,
	StatesAndTerritories_texas	= 12848,
	StatesAndTerritories_utah	= 12849,
	StatesAndTerritories_vermont	= 12850,
	StatesAndTerritories_virginia	= 12851,
	StatesAndTerritories_virgin_Islands	= 12852,
	StatesAndTerritories_washington	= 12853,
	StatesAndTerritories_west_Virginia	= 12854,
	StatesAndTerritories_wisconsin	= 12855,
	StatesAndTerritories_wyoming	= 12856
} e_StatesAndTerritories;

/* StatesAndTerritories */
typedef long	 StatesAndTerritories_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StatesAndTerritories;
asn_struct_free_f StatesAndTerritories_free;
asn_struct_print_f StatesAndTerritories_print;
asn_constr_check_f StatesAndTerritories_constraint;
ber_type_decoder_f StatesAndTerritories_decode_ber;
der_type_encoder_f StatesAndTerritories_encode_der;
xer_type_decoder_f StatesAndTerritories_decode_xer;
xer_type_encoder_f StatesAndTerritories_encode_xer;
oer_type_decoder_f StatesAndTerritories_decode_oer;
oer_type_encoder_f StatesAndTerritories_encode_oer;
per_type_decoder_f StatesAndTerritories_decode_uper;
per_type_encoder_f StatesAndTerritories_encode_uper;
per_type_decoder_f StatesAndTerritories_decode_aper;
per_type_encoder_f StatesAndTerritories_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _StatesAndTerritories_H_ */
#include "asn_internal.h"
