/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "J2540-2-J2540ITIS-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_Temperature_H_
#define	_Temperature_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Temperature {
	Temperature_maximum_temperature	= 5633,
	Temperature_temperature	= 5634,
	Temperature_minimum_temperature	= 5635,
	Temperature_current_temperature	= 5636,
	Temperature_heat_index	= 5637,
	Temperature_extreme_heat	= 5638,
	Temperature_hot	= 5639,
	Temperature_hotter	= 5640,
	Temperature_heat	= 5641,
	Temperature_warmer	= 5642,
	Temperature_warm	= 5643,
	Temperature_mild	= 5644,
	Temperature_cool	= 5645,
	Temperature_cooler	= 5646,
	Temperature_cold	= 5647,
	Temperature_colder	= 5648,
	Temperature_very_cold	= 5649,
	Temperature_extreme_cold	= 5650,
	Temperature_wind_chill	= 5651,
	Temperature_dewpoint	= 5652,
	Temperature_relative_humidity	= 5653,
	Temperature_temperatures_close_to_the_seasonal_norm	= 5758,
	Temperature_less_extreme_temperatures	= 5759
} e_Temperature;

/* Temperature */
typedef long	 Temperature_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Temperature_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Temperature;
asn_struct_free_f Temperature_free;
asn_struct_print_f Temperature_print;
asn_constr_check_f Temperature_constraint;
ber_type_decoder_f Temperature_decode_ber;
der_type_encoder_f Temperature_encode_der;
xer_type_decoder_f Temperature_decode_xer;
xer_type_encoder_f Temperature_encode_xer;
oer_type_decoder_f Temperature_decode_oer;
oer_type_encoder_f Temperature_encode_oer;
per_type_decoder_f Temperature_decode_uper;
per_type_encoder_f Temperature_encode_uper;
per_type_decoder_f Temperature_decode_aper;
per_type_encoder_f Temperature_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Temperature_H_ */
#include "asn_internal.h"
