/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_201603_ASN_CC.asn"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#ifndef	_TrafficControlValue_H_
#define	_TrafficControlValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "NativeEnumerated.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TrafficControlValue_PR {
	TrafficControlValue_PR_NOTHING,	/* No components present */
	TrafficControlValue_PR_value,
	TrafficControlValue_PR_chains,
	TrafficControlValue_PR_direction,
	TrafficControlValue_PR_lataffinity,
	TrafficControlValue_PR_leftperm,
	TrafficControlValue_PR_rightperm,
	TrafficControlValue_PR_opening,
	TrafficControlValue_PR_closing,
	TrafficControlValue_PR_parking
} TrafficControlValue_PR;
typedef enum TrafficControlValue__chains {
	TrafficControlValue__chains_no	= 0,
	TrafficControlValue__chains_permitted	= 1,
	TrafficControlValue__chains_required	= 2
} e_TrafficControlValue__chains;
typedef enum TrafficControlValue__direction {
	TrafficControlValue__direction_forward	= 0,
	TrafficControlValue__direction_reverse	= 1
} e_TrafficControlValue__direction;
typedef enum TrafficControlValue__lataffinity {
	TrafficControlValue__lataffinity_left	= 0,
	TrafficControlValue__lataffinity_right	= 1
} e_TrafficControlValue__lataffinity;
typedef enum TrafficControlValue__leftperm {
	TrafficControlValue__leftperm_none	= 0,
	TrafficControlValue__leftperm_permitted	= 1,
	TrafficControlValue__leftperm_passing_only	= 2,
	TrafficControlValue__leftperm_emergency_only	= 3
} e_TrafficControlValue__leftperm;
typedef enum TrafficControlValue__rightperm {
	TrafficControlValue__rightperm_none	= 0,
	TrafficControlValue__rightperm_permitted	= 1,
	TrafficControlValue__rightperm_passing_only	= 2,
	TrafficControlValue__rightperm_emergency_only	= 3
} e_TrafficControlValue__rightperm;
typedef enum TrafficControlValue__opening {
	TrafficControlValue__opening_left	= 0,
	TrafficControlValue__opening_right	= 1
} e_TrafficControlValue__opening;
typedef enum TrafficControlValue__closing {
	TrafficControlValue__closing_left	= 0,
	TrafficControlValue__closing_right	= 1
} e_TrafficControlValue__closing;
typedef enum TrafficControlValue__parking {
	TrafficControlValue__parking_no	= 0,
	TrafficControlValue__parking_parallel	= 1,
	TrafficControlValue__parking_angled	= 2
} e_TrafficControlValue__parking;

/* TrafficControlValue */
typedef struct TrafficControlValue {
	TrafficControlValue_PR present;
	union TrafficControlValue_u {
		long	 value;
		long	 chains;
		long	 direction;
		long	 lataffinity;
		long	 leftperm;
		long	 rightperm;
		long	 opening;
		long	 closing;
		long	 parking;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrafficControlValue_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_chains_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_direction_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_lataffinity_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_leftperm_13;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_rightperm_18;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_opening_23;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_closing_26;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_parking_29;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_TrafficControlValue;
extern asn_CHOICE_specifics_t asn_SPC_TrafficControlValue_specs_1;
extern asn_TYPE_member_t asn_MBR_TrafficControlValue_1[9];
extern asn_per_constraints_t asn_PER_type_TrafficControlValue_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TrafficControlValue_H_ */
#include "asn_internal.h"
