/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TrafficLightStatusMessage"
 * 	found in "J2735-TrafficLightStatusMessage-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_TrafficLightStatus_H_
#define	_TrafficLightStatus_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TrafficLightType.h"
#include "ConsecutiveTrafficLight.h"
#include "TrafficLightIntervalType.h"
#include "PedestrianCall.h"
#include "ActuatedInterval.h"
#include "PermissiveNonProtected.h"
#include "TrafficLightingStatus.h"
#include "TimeInSecond-B8.h"
#include "TrafficLightDirectionCode.h"
#include "ReservedBit.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TrafficLightStatus */
typedef struct TrafficLightStatus {
	TrafficLightType_t	 trafficLightType;
	ConsecutiveTrafficLight_t	 consecutiveTrafficLight;
	TrafficLightIntervalType_t	 trafficLightIntervalType;
	PedestrianCall_t	 pedestrianCall;
	ActuatedInterval_t	 actuatedinterval;
	PermissiveNonProtected_t	 permissiveNonProtected;
	TrafficLightingStatus_t	 lightingStatus;
	TimeInSecond_B8_t	 maxIntervalLength;
	TimeInSecond_B8_t	 remainingTime;
	TrafficLightDirectionCode_t	 directionCode;
	ReservedBit_t	 reserved;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrafficLightStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrafficLightStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_TrafficLightStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_TrafficLightStatus_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _TrafficLightStatus_H_ */
#include "asn_internal.h"
