/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RoadUserChargingReportMessage"
 * 	found in "J3217-R-RoadUserChargingReportMsg-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_UsageReport_H_
#define	_UsageReport_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FeeReport.h"
#include "ItemizedPaymentReport.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UsageReport_PR {
	UsageReport_PR_NOTHING,	/* No components present */
	UsageReport_PR_feeReport,
	UsageReport_PR_itemizedPaymentReport
	/* Extensions may appear below */
	
} UsageReport_PR;

/* UsageReport */
typedef struct UsageReport {
	UsageReport_PR present;
	union UsageReport_u {
		FeeReport_t	 feeReport;
		ItemizedPaymentReport_t	 itemizedPaymentReport;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UsageReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UsageReport;
extern asn_CHOICE_specifics_t asn_SPC_UsageReport_specs_1;
extern asn_TYPE_member_t asn_MBR_UsageReport_1[2];
extern asn_per_constraints_t asn_PER_type_UsageReport_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _UsageReport_H_ */
#include "asn_internal.h"
