FROM php:apache

# Enable required Apache modules
RUN a2enmod ssl \
    && a2enmod rewrite \
    && a2enmod proxy \
    && a2enmod proxy_http \
    && a2enmod proxy_wstunnel

COPY docker/000-default.conf /etc/apache2/sites-available/000-default.conf

COPY web/ /var/www/html/
