
/**
 * WARNING: DO NOT EDIT THIS FILE
 *
 * This source file was generated from the CPlusPlusGenerator.xsl stylesheet
 *
 * Your changes will be overwritten when this tool executes again.  In order
 * to edit the contents, you must go into the source XML files
 *
 * @author Greg Baumgardner
 */
 

#ifndef INCLUDE_VEHICLEPARAMETERENUMTYPES_H_
#define INCLUDE_VEHICLEPARAMETERENUMTYPES_H_

#ifndef CONSTEXPR
#if __cplusplus > 199711L
#define CONSTEXPR constexpr
#else
#ifdef __GNUC__
#define CONSTEXPR __attribute__ ((unused))
#else
#define CONSTEXPR
#endif
#endif
#endif

		
	
namespace tmx {
		
namespace messages {
			
namespace vehicleparam {
				
			
enum GearState 
{
		GearUnknown = 0,
		Park = 1,
		Reverse = 2,
		Drive = 3,
		Other = 4
};
		
		
static CONSTEXPR const char *GEARSTATE_GEARUNKNOWN_STRING = "GearUnknown";
static CONSTEXPR const char *GEARSTATE_PARK_STRING = "Park";
static CONSTEXPR const char *GEARSTATE_REVERSE_STRING = "Reverse";
static CONSTEXPR const char *GEARSTATE_DRIVE_STRING = "Drive";
static CONSTEXPR const char *GEARSTATE_OTHER_STRING = "Other";
			
enum TurnSignalState 
{
		SignalUnknown = 0,
		Off = 1,
		Left = 2,
		Right = 3
};
		
		
static CONSTEXPR const char *TURNSIGNALSTATE_SIGNALUNKNOWN_STRING = "SignalUnknown";
static CONSTEXPR const char *TURNSIGNALSTATE_OFF_STRING = "Off";
static CONSTEXPR const char *TURNSIGNALSTATE_LEFT_STRING = "Left";
static CONSTEXPR const char *TURNSIGNALSTATE_RIGHT_STRING = "Right";
			
enum VehicleParameter 
{
		ParameterNA = 0,
		GearPosition = 1,
		TurnSignal = 2,
		Brake = 3
};
		
		
static CONSTEXPR const char *VEHICLEPARAMETER_PARAMETERNA_STRING = "ParameterNA";
static CONSTEXPR const char *VEHICLEPARAMETER_GEARPOSITION_STRING = "GearPosition";
static CONSTEXPR const char *VEHICLEPARAMETER_TURNSIGNAL_STRING = "TurnSignal";
static CONSTEXPR const char *VEHICLEPARAMETER_BRAKE_STRING = "Brake";
			
enum VehicleParameterState 
{
		StateNA = 0,
		Gear_Park = 1,
		Gear_Reverse = 2,
		Gear_Drive = 3,
		Gear_Other = 4,
		Turn_Off = 5,
		Turn_Left = 6,
		Turn_Right = 7,
		Brake_On = 8,
		Brake_Off = 9
};
		
		
static CONSTEXPR const char *VEHICLEPARAMETERSTATE_STATENA_STRING = "StateNA";
static CONSTEXPR const char *VEHICLEPARAMETERSTATE_GEAR_PARK_STRING = "Gear_Park";
static CONSTEXPR const char *VEHICLEPARAMETERSTATE_GEAR_REVERSE_STRING = "Gear_Reverse";
static CONSTEXPR const char *VEHICLEPARAMETERSTATE_GEAR_DRIVE_STRING = "Gear_Drive";
static CONSTEXPR const char *VEHICLEPARAMETERSTATE_GEAR_OTHER_STRING = "Gear_Other";
static CONSTEXPR const char *VEHICLEPARAMETERSTATE_TURN_OFF_STRING = "Turn_Off";
static CONSTEXPR const char *VEHICLEPARAMETERSTATE_TURN_LEFT_STRING = "Turn_Left";
static CONSTEXPR const char *VEHICLEPARAMETERSTATE_TURN_RIGHT_STRING = "Turn_Right";
static CONSTEXPR const char *VEHICLEPARAMETERSTATE_BRAKE_ON_STRING = "Brake_On";
static CONSTEXPR const char *VEHICLEPARAMETERSTATE_BRAKE_OFF_STRING = "Brake_Off";
			
} /* End namespace vehicleparam */
		
} /* End namespace messages */
	
} /* End namespace tmx */

		
#endif /* INCLUDE_VEHICLEPARAMETERENUMTYPES_H_ */
	