openapi: 3.0.0
info:
  title: Pedestrian Webservice
  description: Webservice registers pedestrian request for going through intersection 
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: V2X-Hub server
paths:
  /pedestrian:
    post:
      summary: Add pedestrian request to queue.
      description: registers pedestrian post request that includes heading and geographic location.
      requestBody:
        description: heading and geographic location of PSM
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PSM'
      responses:
        '201':
          description: Created                  
components:
  schemas:
    PSM:
      title: A PSM message
      type: object
      properties:
	id:
	  type: int
          description: ID of PSM
        lon:
          type: double
          description: longitude of PSM
        lat:
          type: double
          description: latitude of PSM
        heading:
          type: double
          description: heading of PSM
      required:
        - lon
        - lat
        - heading
