/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../J2735_R41_Source_mod.ASN"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#ifndef	_ExitService_H_
#define	_ExitService_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "ITIScodes.h"
#include "IA5String.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum item_es_PR {
	item_es_PR_NOTHING,	/* No components present */
	item_es_PR_itis,
	item_es_PR_text
} item_es_PR;

/* ExitService */
typedef struct ExitService {
	A_SEQUENCE_OF(struct ExitService__Member {
		struct item_es {
			item_es_PR present;
			union item_es_u {
				ITIScodes_t	 itis;
				IA5String_t	 text;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} item_es;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExitService_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExitService;

#ifdef __cplusplus
}
#endif

#endif	/* _ExitService_H_ */
#include "asn_internal.h"
