/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "JPN"
 * 	found in "../J2735_R41_Source_mod.ASN"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#ifndef	_JPN_Reg_LaneDataAttribute_H_
#define	_JPN_Reg_LaneDataAttribute_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* JPN-Reg-LaneDataAttribute */
typedef struct JPN_Reg_LaneDataAttribute {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} JPN_Reg_LaneDataAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_JPN_Reg_LaneDataAttribute;

#ifdef __cplusplus
}
#endif

#endif	/* _JPN_Reg_LaneDataAttribute_H_ */
#include "asn_internal.h"
