/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../J2735_R41_Source_mod_with_PSM.ASN"
 * 	`asn1c -gen-PER -fno-include-deps`
 */

#ifndef	_PersonalMobilityMessage_H_
#define	_PersonalMobilityMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "UUIDType.h"
#include "RequestID.h"
#include "PersonalMobilityMessageStatusType.h"
#include "Position3D.h"
#include "PositionalAccuracy.h"
#include "ModeOfTransportType.h"
#include "EstimatedTimeType.h"
#include "DSRCEquippedType.h"
#include "VehicleDescriptionType.h"
#include "RegionalPersonalMobilityMessage.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DFullTime;
struct DestinationType;
struct MobilityNeedsList;

/* PersonalMobilityMessage */
typedef struct PersonalMobilityMessage {
	UUIDType_t	 groupId;
	RequestID_t	 requestId;
	PersonalMobilityMessageStatusType_t	 status;
	Position3D_t	 position;
	PositionalAccuracy_t	*accuracy	/* OPTIONAL */;
	struct DFullTime	*requestDate	/* OPTIONAL */;
	struct DFullTime	*pickupDate	/* OPTIONAL */;
	struct DestinationType	*destination	/* OPTIONAL */;
	struct MobilityNeedsList	*mobilityNeeds	/* OPTIONAL */;
	ModeOfTransportType_t	*modeOfTransport	/* OPTIONAL */;
	EstimatedTimeType_t	*eta	/* OPTIONAL */;
	DSRCEquippedType_t	*isDSRCEquipped	/* OPTIONAL */;
	VehicleDescriptionType_t	*vehicleDesc	/* OPTIONAL */;
	RegionalPersonalMobilityMessage_t	 regional;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PersonalMobilityMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PersonalMobilityMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _PersonalMobilityMessage_H_ */
#include "asn_internal.h"
