/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../J2735_R41_Source_mod.ASN"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#ifndef	_RegionalPosition3D_H_
#define	_RegionalPosition3D_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Reg-Position3D.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RegionalPosition3D */
typedef Reg_Position3D_t	 RegionalPosition3D_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionalPosition3D;
asn_struct_free_f RegionalPosition3D_free;
asn_struct_print_f RegionalPosition3D_print;
asn_constr_check_f RegionalPosition3D_constraint;
ber_type_decoder_f RegionalPosition3D_decode_ber;
der_type_encoder_f RegionalPosition3D_encode_der;
xer_type_decoder_f RegionalPosition3D_decode_xer;
xer_type_encoder_f RegionalPosition3D_encode_xer;
per_type_decoder_f RegionalPosition3D_decode_uper;
per_type_encoder_f RegionalPosition3D_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RegionalPosition3D_H_ */
#include "asn_internal.h"
