/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../J2735_R41_Source_mod.ASN"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#ifndef	_RegionalMovementState_H_
#define	_RegionalMovementState_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Reg-MovementState.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RegionalMovementState */
typedef Reg_MovementState_t	 RegionalMovementState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionalMovementState;
asn_struct_free_f RegionalMovementState_free;
asn_struct_print_f RegionalMovementState_print;
asn_constr_check_f RegionalMovementState_constraint;
ber_type_decoder_f RegionalMovementState_decode_ber;
der_type_encoder_f RegionalMovementState_encode_der;
xer_type_decoder_f RegionalMovementState_decode_xer;
xer_type_encoder_f RegionalMovementState_encode_xer;
per_type_decoder_f RegionalMovementState_decode_uper;
per_type_encoder_f RegionalMovementState_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RegionalMovementState_H_ */
#include "asn_internal.h"
