/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../J2735_R41_Source_mod.ASN"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#ifndef	_RegulatorySpeedLimit_H_
#define	_RegulatorySpeedLimit_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SpeedLimitType.h"
#include "Velocity.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RegulatorySpeedLimit */
typedef struct RegulatorySpeedLimit {
	SpeedLimitType_t	 type;
	Velocity_t	 speed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegulatorySpeedLimit_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegulatorySpeedLimit;

#ifdef __cplusplus
}
#endif

#endif	/* _RegulatorySpeedLimit_H_ */
#include "asn_internal.h"
