/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../J2735_R41_Source_mod.ASN"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#ifndef	_SignalGroupID_H_
#define	_SignalGroupID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SignalGroupID */
typedef long	 SignalGroupID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalGroupID;
asn_struct_free_f SignalGroupID_free;
asn_struct_print_f SignalGroupID_print;
asn_constr_check_f SignalGroupID_constraint;
ber_type_decoder_f SignalGroupID_decode_ber;
der_type_encoder_f SignalGroupID_encode_der;
xer_type_decoder_f SignalGroupID_decode_xer;
xer_type_encoder_f SignalGroupID_encode_xer;
per_type_decoder_f SignalGroupID_decode_uper;
per_type_encoder_f SignalGroupID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalGroupID_H_ */
#include "asn_internal.h"
