/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../J2735_R41_Source_mod_with_PSM.ASN"
 * 	`asn1c -gen-PER -fno-include-deps`
 */

#include "PersonalMobilityMessage.h"

#include "DFullTime.h"
#include "DestinationType.h"
#include "MobilityNeedsList.h"
static asn_TYPE_member_t asn_MBR_PersonalMobilityMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PersonalMobilityMessage, groupId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UUIDType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"groupId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PersonalMobilityMessage, requestId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RequestID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"requestId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PersonalMobilityMessage, status),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PersonalMobilityMessageStatusType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"status"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PersonalMobilityMessage, position),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Position3D,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"position"
		},
	{ ATF_POINTER, 9, offsetof(struct PersonalMobilityMessage, accuracy),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositionalAccuracy,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"accuracy"
		},
	{ ATF_POINTER, 8, offsetof(struct PersonalMobilityMessage, requestDate),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DFullTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"requestDate"
		},
	{ ATF_POINTER, 7, offsetof(struct PersonalMobilityMessage, pickupDate),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DFullTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"pickupDate"
		},
	{ ATF_POINTER, 6, offsetof(struct PersonalMobilityMessage, destination),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DestinationType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"destination"
		},
	{ ATF_POINTER, 5, offsetof(struct PersonalMobilityMessage, mobilityNeeds),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MobilityNeedsList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mobilityNeeds"
		},
	{ ATF_POINTER, 4, offsetof(struct PersonalMobilityMessage, modeOfTransport),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ModeOfTransportType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"modeOfTransport"
		},
	{ ATF_POINTER, 3, offsetof(struct PersonalMobilityMessage, eta),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EstimatedTimeType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eta"
		},
	{ ATF_POINTER, 2, offsetof(struct PersonalMobilityMessage, isDSRCEquipped),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRCEquippedType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"isDSRCEquipped"
		},
	{ ATF_POINTER, 1, offsetof(struct PersonalMobilityMessage, vehicleDesc),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleDescriptionType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"vehicleDesc"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PersonalMobilityMessage, regional),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionalPersonalMobilityMessage,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"regional"
		},
};
static const int asn_MAP_PersonalMobilityMessage_oms_1[] = { 4, 5, 6, 7, 8, 9, 10, 11, 12 };
static const ber_tlv_tag_t asn_DEF_PersonalMobilityMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PersonalMobilityMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* groupId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* requestId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* status */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* position */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* accuracy */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* requestDate */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* pickupDate */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* destination */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* mobilityNeeds */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* modeOfTransport */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* eta */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* isDSRCEquipped */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* vehicleDesc */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 } /* regional */
};
static asn_SEQUENCE_specifics_t asn_SPC_PersonalMobilityMessage_specs_1 = {
	sizeof(struct PersonalMobilityMessage),
	offsetof(struct PersonalMobilityMessage, _asn_ctx),
	asn_MAP_PersonalMobilityMessage_tag2el_1,
	14,	/* Count of tags in the map */
	asn_MAP_PersonalMobilityMessage_oms_1,	/* Optional members */
	9, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PersonalMobilityMessage = {
	"PersonalMobilityMessage",
	"PersonalMobilityMessage",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PersonalMobilityMessage_tags_1,
	sizeof(asn_DEF_PersonalMobilityMessage_tags_1)
		/sizeof(asn_DEF_PersonalMobilityMessage_tags_1[0]), /* 1 */
	asn_DEF_PersonalMobilityMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_PersonalMobilityMessage_tags_1)
		/sizeof(asn_DEF_PersonalMobilityMessage_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PersonalMobilityMessage_1,
	14,	/* Elements count */
	&asn_SPC_PersonalMobilityMessage_specs_1	/* Additional specs */
};

