/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EU"
 * 	found in "../J2735_R41_Source_mod.ASN"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#include "SignalHeadLocation.h"

static asn_TYPE_member_t asn_MBR_SignalHeadLocation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignalHeadLocation, node),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NodeOffsetPoint,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"node"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignalHeadLocation, signalGroupID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignalGroupID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"signalGroupID"
		},
};
static ber_tlv_tag_t asn_DEF_SignalHeadLocation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SignalHeadLocation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* node */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* signalGroupID */
};
static asn_SEQUENCE_specifics_t asn_SPC_SignalHeadLocation_specs_1 = {
	sizeof(struct SignalHeadLocation),
	offsetof(struct SignalHeadLocation, _asn_ctx),
	asn_MAP_SignalHeadLocation_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SignalHeadLocation = {
	"SignalHeadLocation",
	"SignalHeadLocation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SignalHeadLocation_tags_1,
	sizeof(asn_DEF_SignalHeadLocation_tags_1)
		/sizeof(asn_DEF_SignalHeadLocation_tags_1[0]), /* 1 */
	asn_DEF_SignalHeadLocation_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignalHeadLocation_tags_1)
		/sizeof(asn_DEF_SignalHeadLocation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SignalHeadLocation_1,
	2,	/* Elements count */
	&asn_SPC_SignalHeadLocation_specs_1	/* Additional specs */
};

