/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../J2735_R41_Source_mod.ASN"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted`
 */

#include "ValidRegion.h"

static asn_per_constraints_t asn_PER_type_area_constr_4 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_area_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ValidRegion__area, choice.shapePointSet),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ShapePointSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"shapePointSet"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ValidRegion__area, choice.circle),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Circle,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"circle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ValidRegion__area, choice.regionPointSet),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionPointSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"regionPointSet"
		},
};
static asn_TYPE_tag2member_t asn_MAP_area_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* shapePointSet */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* circle */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* regionPointSet */
};
static asn_CHOICE_specifics_t asn_SPC_area_specs_4 = {
	sizeof(struct ValidRegion__area),
	offsetof(struct ValidRegion__area, _asn_ctx),
	offsetof(struct ValidRegion__area, present),
	sizeof(((struct ValidRegion__area *)0)->present),
	asn_MAP_area_tag2el_4,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_area_4 = {
	"area",
	"area",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_area_constr_4,
	asn_MBR_area_4,
	3,	/* Elements count */
	&asn_SPC_area_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ValidRegion_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ValidRegion, direction),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HeadingSlice,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"direction"
		},
	{ ATF_POINTER, 1, offsetof(struct ValidRegion, extent),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Extent,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"extent"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ValidRegion, area),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_area_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"area"
		},
};
static int asn_MAP_ValidRegion_oms_1[] = { 1 };
static ber_tlv_tag_t asn_DEF_ValidRegion_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ValidRegion_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* direction */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* extent */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* area */
};
static asn_SEQUENCE_specifics_t asn_SPC_ValidRegion_specs_1 = {
	sizeof(struct ValidRegion),
	offsetof(struct ValidRegion, _asn_ctx),
	asn_MAP_ValidRegion_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ValidRegion_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ValidRegion = {
	"ValidRegion",
	"ValidRegion",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ValidRegion_tags_1,
	sizeof(asn_DEF_ValidRegion_tags_1)
		/sizeof(asn_DEF_ValidRegion_tags_1[0]), /* 1 */
	asn_DEF_ValidRegion_tags_1,	/* Same as above */
	sizeof(asn_DEF_ValidRegion_tags_1)
		/sizeof(asn_DEF_ValidRegion_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ValidRegion_1,
	3,	/* Elements count */
	&asn_SPC_ValidRegion_specs_1	/* Additional specs */
};

