//==========================================================================
// Name        : PedestrianPlugin.cpp
// Author      : FHWA Saxton Transportation Operations Laboratory  
// Version     :
// Copyright   : Copyright (c) 2024 FHWA Saxton Transportation Operations Laboratory. All rights reserved.
// Description : Pedestrian Plugin
//==========================================================================
#pragma once
#include <string>

#include <PluginClientClockAware.h>

#include <atomic>
#include <thread>
#include <mutex>
#include <iostream>
#include <sstream>
#include <unordered_set>
#include <algorithm>
#include <queue>
#include "FLIRWebSockAsyncClnSession.hpp"
#include "FLIRConfigurations.hpp"


namespace FLIRCameraDriverPlugin
{

	/**
	 * @brief Plugin used to encode messages from an XML input via HTTP POST or metadata received from the FLIR API.
	 */
	class FLIRCameraDriverPlugin: public tmx::utils::PluginClientClockAware
	{
		public:
			explicit FLIRCameraDriverPlugin(const std::string &name);
			int Main() override;

		protected:
			/**
			 * @brief Called everytime a configuration value is changed for the plugin.
			 */
			void UpdateConfigSettings();
			// Virtual method overrides START
			/**
			 * @brief Overrides PluginClient OnConfigChanged(const char *key, const char *value) method
			 * and calls UpdateConfigSettings() on each configuration change.
			 * @param key string key of the configuration value that has changed.
			 * @param value new value of the configuration that has changed.
			 */
			void OnConfigChanged(const char *key, const char *value) override;
			/**
			 * @brief Overrides PluginClient OnStateChange(IvpPluginState state) method.
			 * @param state new state of the plugin.
			 */
			void OnStateChange(IvpPluginState state) override;
			// Virtual method overrides END.

			/**
			 * @brief Add DSRC metadata to messages and broadcast pedestrian detection information.
			 * @param msgJson PSM, SDSM, or TIM in XML string format.
			 */
			void BroadcastPedDet(const std::string &msgXML);

			/**
			 * @brief Starts WebService to handle incoming HTTP POST requests.
			 */
			int  StartWebService();
			/**
			 * @brief Starts Asyncronous WebSocket Client to connect to FLIR WebSocket Server.
			 */
			int  StartWebSocket(const FLIRConfiguration &config);
			/**
			 * @brief Stops WebService before FLIR WebSocket enabled. 
			 */
			void StopWebService();
			/**
			 * @brief Stops WebSocket Client session before HTTP POST WebService is enabled. 
			 */
			void StopWebSocket();
			
			/**
			 * @brief Sends new XMLs generated by FLIR WebSocket session to BroadcastPedDet.
			 */
			void checkXML();
			/**
			 * @brief Parses messages received into BroadcastPedDet to check what kind of message it is (e.g. PSM, SDSM, TIM).
			 * @param message Message XML as a string.
			 */
			std::string parseMessage(const std::string& message) const;
			/**
			 * @brief Parses though user configurations to determine which message(s) to generate. Accepts any combination of PSM, SDSM, and/or TIM. 
			 */
			void getMessageToWrite();

			
		private:
			
			std::mutex _cfgLock;
			
			uint16_t webport;
			std::string webip; 
			std::string dataprovider;
			std::vector<std::shared_ptr<FLIRWebSockAsyncClnSession>> flirSessions;
			std::shared_ptr<FLIRConfigurations> flirConfigsPtr;
			std::string flirOutput;
			bool runningWebSocket = false;
	};

}
