/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeDataConfig"
 * 	found in "J2945-C-ProbeDataConfig-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_CfgInterval_H_
#define	_CfgInterval_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CfgInterval_PR {
	CfgInterval_PR_NOTHING,	/* No components present */
	CfgInterval_PR_timeInterval,
	CfgInterval_PR_distanceInterval
	/* Extensions may appear below */
	
} CfgInterval_PR;

/* CfgInterval */
typedef struct CfgInterval {
	CfgInterval_PR present;
	union CfgInterval_u {
		long	 timeInterval;
		long	 distanceInterval;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CfgInterval_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CfgInterval;
extern asn_CHOICE_specifics_t asn_SPC_CfgInterval_specs_1;
extern asn_TYPE_member_t asn_MBR_CfgInterval_1[2];
extern asn_per_constraints_t asn_PER_type_CfgInterval_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CfgInterval_H_ */
#include "asn_internal.h"
