/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeDataConfig"
 * 	found in "J2945-C-ProbeDataConfig-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#include "ConfigTemporalBoundary.h"

asn_TYPE_member_t asn_MBR_ConfigTemporalBoundary_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConfigTemporalBoundary, beginTime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DDateTime,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"beginTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfigTemporalBoundary, endTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DDateTime,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"endTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfigTemporalBoundary, recurring),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CfgEventRecurrence,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"recurring"
		},
};
static const ber_tlv_tag_t asn_DEF_ConfigTemporalBoundary_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ConfigTemporalBoundary_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* beginTime */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* endTime */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* recurring */
};
asn_SEQUENCE_specifics_t asn_SPC_ConfigTemporalBoundary_specs_1 = {
	sizeof(struct ConfigTemporalBoundary),
	offsetof(struct ConfigTemporalBoundary, _asn_ctx),
	asn_MAP_ConfigTemporalBoundary_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ConfigTemporalBoundary = {
	"ConfigTemporalBoundary",
	"ConfigTemporalBoundary",
	&asn_OP_SEQUENCE,
	asn_DEF_ConfigTemporalBoundary_tags_1,
	sizeof(asn_DEF_ConfigTemporalBoundary_tags_1)
		/sizeof(asn_DEF_ConfigTemporalBoundary_tags_1[0]), /* 1 */
	asn_DEF_ConfigTemporalBoundary_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConfigTemporalBoundary_tags_1)
		/sizeof(asn_DEF_ConfigTemporalBoundary_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ConfigTemporalBoundary_1,
	3,	/* Elements count */
	&asn_SPC_ConfigTemporalBoundary_specs_1	/* Additional specs */
};

