/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "J2735-Common-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_DescriptionOfRoadSurface_H_
#define	_DescriptionOfRoadSurface_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PortlandCement.h"
#include "AsphaltOrTar.h"
#include "Gravel.h"
#include "Grass.h"
#include "Cinders.h"
#include "Rock.h"
#include "Ice.h"
#include "Snow.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DescriptionOfRoadSurface_PR {
	DescriptionOfRoadSurface_PR_NOTHING,	/* No components present */
	DescriptionOfRoadSurface_PR_portlandCement,
	DescriptionOfRoadSurface_PR_asphaltOrTar,
	DescriptionOfRoadSurface_PR_gravel,
	DescriptionOfRoadSurface_PR_grass,
	DescriptionOfRoadSurface_PR_cinders,
	DescriptionOfRoadSurface_PR_rock,
	DescriptionOfRoadSurface_PR_ice,
	DescriptionOfRoadSurface_PR_snow
	/* Extensions may appear below */
	
} DescriptionOfRoadSurface_PR;

/* DescriptionOfRoadSurface */
typedef struct DescriptionOfRoadSurface {
	DescriptionOfRoadSurface_PR present;
	union DescriptionOfRoadSurface_u {
		PortlandCement_t	 portlandCement;
		AsphaltOrTar_t	 asphaltOrTar;
		Gravel_t	 gravel;
		Grass_t	 grass;
		Cinders_t	 cinders;
		Rock_t	 rock;
		Ice_t	 ice;
		Snow_t	 snow;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DescriptionOfRoadSurface_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DescriptionOfRoadSurface;
extern asn_CHOICE_specifics_t asn_SPC_DescriptionOfRoadSurface_specs_1;
extern asn_TYPE_member_t asn_MBR_DescriptionOfRoadSurface_1[8];
extern asn_per_constraints_t asn_PER_type_DescriptionOfRoadSurface_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _DescriptionOfRoadSurface_H_ */
#include "asn_internal.h"
