/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "ISO17573-EfcDataDictionary.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_EfcDataDictionary_Latitude_H_
#define	_EfcDataDictionary_Latitude_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Int4Signed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EfcDataDictionary_Latitude */
typedef Int4Signed_t	 EfcDataDictionary_Latitude_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EfcDataDictionary_Latitude_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EfcDataDictionary_Latitude;
asn_struct_free_f EfcDataDictionary_Latitude_free;
asn_struct_print_f EfcDataDictionary_Latitude_print;
asn_constr_check_f EfcDataDictionary_Latitude_constraint;
ber_type_decoder_f EfcDataDictionary_Latitude_decode_ber;
der_type_encoder_f EfcDataDictionary_Latitude_encode_der;
xer_type_decoder_f EfcDataDictionary_Latitude_decode_xer;
xer_type_encoder_f EfcDataDictionary_Latitude_encode_xer;
oer_type_decoder_f EfcDataDictionary_Latitude_decode_oer;
oer_type_encoder_f EfcDataDictionary_Latitude_encode_oer;
per_type_decoder_f EfcDataDictionary_Latitude_decode_uper;
per_type_encoder_f EfcDataDictionary_Latitude_encode_uper;
per_type_decoder_f EfcDataDictionary_Latitude_decode_aper;
per_type_encoder_f EfcDataDictionary_Latitude_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EfcDataDictionary_Latitude_H_ */
#include "asn_internal.h"
