/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "J2540ITIS"
 * 	found in "J2540-2-J2540ITIS-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_LargeNumbers_H_
#define	_LargeNumbers_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LargeNumbers {
	LargeNumbers_n1_16th	= 11521,
	LargeNumbers_n1_10th	= 11522,
	LargeNumbers_n1_8th	= 11523,
	LargeNumbers_n1_4th	= 11524,
	LargeNumbers_n1_3rd	= 11525,
	LargeNumbers_n1_2	= 11526,
	LargeNumbers_n3_4	= 11527,
	LargeNumbers_n300	= 11531,
	LargeNumbers_n350	= 11532,
	LargeNumbers_n400	= 11533,
	LargeNumbers_n450	= 11534,
	LargeNumbers_n500	= 11535,
	LargeNumbers_n550	= 11536,
	LargeNumbers_n600	= 11537,
	LargeNumbers_n650	= 11538,
	LargeNumbers_n700	= 11539,
	LargeNumbers_n750	= 11540,
	LargeNumbers_n800	= 11541,
	LargeNumbers_n850	= 11542,
	LargeNumbers_n900	= 11543,
	LargeNumbers_n950	= 11544,
	LargeNumbers_n1000	= 11545,
	LargeNumbers_n1100	= 11546,
	LargeNumbers_n1200	= 11547,
	LargeNumbers_n1300	= 11548,
	LargeNumbers_n1400	= 11549,
	LargeNumbers_n1500	= 11550,
	LargeNumbers_n1600	= 11551,
	LargeNumbers_n1700	= 11552,
	LargeNumbers_n1800	= 11553,
	LargeNumbers_n1900	= 11554,
	LargeNumbers_n2000	= 11555,
	LargeNumbers_n2100	= 11556,
	LargeNumbers_n2200	= 11557,
	LargeNumbers_n2300	= 11558,
	LargeNumbers_n2400	= 11559,
	LargeNumbers_n2500	= 11560,
	LargeNumbers_n2600	= 11561,
	LargeNumbers_n2700	= 11562,
	LargeNumbers_n2800	= 11563,
	LargeNumbers_n2900	= 11564,
	LargeNumbers_n3000	= 11565,
	LargeNumbers_n3500	= 11566,
	LargeNumbers_n4000	= 11567,
	LargeNumbers_n4500	= 11568,
	LargeNumbers_n5000	= 11569,
	LargeNumbers_n5500	= 11570,
	LargeNumbers_n6000	= 11571,
	LargeNumbers_n6500	= 11572,
	LargeNumbers_n7000	= 11573,
	LargeNumbers_n7500	= 11574,
	LargeNumbers_n8000	= 11575,
	LargeNumbers_n8500	= 11576,
	LargeNumbers_n9000	= 11577,
	LargeNumbers_n9500	= 11578,
	LargeNumbers_n10000	= 11579,
	LargeNumbers_n11000	= 11580,
	LargeNumbers_n12000	= 11581,
	LargeNumbers_n13000	= 11582,
	LargeNumbers_n14000	= 11583,
	LargeNumbers_n15000	= 11584,
	LargeNumbers_n16000	= 11585,
	LargeNumbers_n17000	= 11586,
	LargeNumbers_n18000	= 11587,
	LargeNumbers_n19000	= 11588,
	LargeNumbers_n20000	= 11589,
	LargeNumbers_n21000	= 11590,
	LargeNumbers_n22000	= 11591,
	LargeNumbers_n23000	= 11592,
	LargeNumbers_n24000	= 11593,
	LargeNumbers_n25000	= 11594,
	LargeNumbers_n26000	= 11595,
	LargeNumbers_n27000	= 11596,
	LargeNumbers_n28000	= 11597,
	LargeNumbers_n29000	= 11598,
	LargeNumbers_n30000	= 11599,
	LargeNumbers_n35000	= 11600,
	LargeNumbers_n40000	= 11601,
	LargeNumbers_n45000	= 11602,
	LargeNumbers_n50000	= 11603,
	LargeNumbers_n55000	= 11604,
	LargeNumbers_n60000	= 11605,
	LargeNumbers_n65000	= 11606,
	LargeNumbers_n70000	= 11607,
	LargeNumbers_n75000	= 11608,
	LargeNumbers_n80000	= 11609,
	LargeNumbers_n85000	= 11610,
	LargeNumbers_n90000	= 11611,
	LargeNumbers_n95000	= 11612,
	LargeNumbers_n100000	= 11613
} e_LargeNumbers;

/* LargeNumbers */
typedef long	 LargeNumbers_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LargeNumbers;
asn_struct_free_f LargeNumbers_free;
asn_struct_print_f LargeNumbers_print;
asn_constr_check_f LargeNumbers_constraint;
ber_type_decoder_f LargeNumbers_decode_ber;
der_type_encoder_f LargeNumbers_encode_der;
xer_type_decoder_f LargeNumbers_decode_xer;
xer_type_encoder_f LargeNumbers_encode_xer;
oer_type_decoder_f LargeNumbers_decode_oer;
oer_type_encoder_f LargeNumbers_encode_oer;
per_type_decoder_f LargeNumbers_decode_uper;
per_type_encoder_f LargeNumbers_encode_uper;
per_type_decoder_f LargeNumbers_decode_aper;
per_type_encoder_f LargeNumbers_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LargeNumbers_H_ */
#include "asn_internal.h"
