/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "ISO17573-EfcDataDictionary.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_LocationClassId_H_
#define	_LocationClassId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Int4Unsigned.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LocationClassId */
typedef Int4Unsigned_t	 LocationClassId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LocationClassId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LocationClassId;
asn_struct_free_f LocationClassId_free;
asn_struct_print_f LocationClassId_print;
asn_constr_check_f LocationClassId_constraint;
ber_type_decoder_f LocationClassId_decode_ber;
der_type_encoder_f LocationClassId_encode_der;
xer_type_decoder_f LocationClassId_decode_xer;
xer_type_encoder_f LocationClassId_encode_xer;
oer_type_decoder_f LocationClassId_decode_oer;
oer_type_encoder_f LocationClassId_encode_oer;
per_type_decoder_f LocationClassId_decode_uper;
per_type_encoder_f LocationClassId_encode_uper;
per_type_decoder_f LocationClassId_decode_aper;
per_type_encoder_f LocationClassId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LocationClassId_H_ */
#include "asn_internal.h"
