/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RoadWeatherMessage"
 * 	found in "J2945-3-RoadWeatherMessage-2024-rel-v2.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_NTCIPEssVisibilitySituation_H_
#define	_NTCIPEssVisibilitySituation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NTCIPEssVisibilitySituation {
	NTCIPEssVisibilitySituation_other	= 1,
	NTCIPEssVisibilitySituation_unknown	= 2,
	NTCIPEssVisibilitySituation_clear	= 3,
	NTCIPEssVisibilitySituation_fogNotPatchy	= 4,
	NTCIPEssVisibilitySituation_patchyFog	= 5,
	NTCIPEssVisibilitySituation_blowingSnow	= 6,
	NTCIPEssVisibilitySituation_smoke	= 7,
	NTCIPEssVisibilitySituation_seaSpray	= 8,
	NTCIPEssVisibilitySituation_vehicleSpray	= 9,
	NTCIPEssVisibilitySituation_blowingDustOrSand	= 10,
	NTCIPEssVisibilitySituation_sunGlare	= 11,
	NTCIPEssVisibilitySituation_swarmsOfInsects	= 12
	/*
	 * Enumeration is extensible
	 */
} e_NTCIPEssVisibilitySituation;

/* NTCIPEssVisibilitySituation */
typedef long	 NTCIPEssVisibilitySituation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NTCIPEssVisibilitySituation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NTCIPEssVisibilitySituation;
extern const asn_INTEGER_specifics_t asn_SPC_NTCIPEssVisibilitySituation_specs_1;
asn_struct_free_f NTCIPEssVisibilitySituation_free;
asn_struct_print_f NTCIPEssVisibilitySituation_print;
asn_constr_check_f NTCIPEssVisibilitySituation_constraint;
ber_type_decoder_f NTCIPEssVisibilitySituation_decode_ber;
der_type_encoder_f NTCIPEssVisibilitySituation_encode_der;
xer_type_decoder_f NTCIPEssVisibilitySituation_decode_xer;
xer_type_encoder_f NTCIPEssVisibilitySituation_encode_xer;
oer_type_decoder_f NTCIPEssVisibilitySituation_decode_oer;
oer_type_encoder_f NTCIPEssVisibilitySituation_encode_oer;
per_type_decoder_f NTCIPEssVisibilitySituation_decode_uper;
per_type_encoder_f NTCIPEssVisibilitySituation_encode_uper;
per_type_decoder_f NTCIPEssVisibilitySituation_decode_aper;
per_type_encoder_f NTCIPEssVisibilitySituation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NTCIPEssVisibilitySituation_H_ */
#include "asn_internal.h"
