/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RoadWeatherMessage"
 * 	found in "J2945-3-RoadWeatherMessage-2024-rel-v2.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_NTCIPEssPaveTreatmentWidth_H_
#define	_NTCIPEssPaveTreatmentWidth_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NTCIPEssPaveTreatmentWidth */
typedef long	 NTCIPEssPaveTreatmentWidth_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NTCIPEssPaveTreatmentWidth_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NTCIPEssPaveTreatmentWidth;
asn_struct_free_f NTCIPEssPaveTreatmentWidth_free;
asn_struct_print_f NTCIPEssPaveTreatmentWidth_print;
asn_constr_check_f NTCIPEssPaveTreatmentWidth_constraint;
ber_type_decoder_f NTCIPEssPaveTreatmentWidth_decode_ber;
der_type_encoder_f NTCIPEssPaveTreatmentWidth_encode_der;
xer_type_decoder_f NTCIPEssPaveTreatmentWidth_decode_xer;
xer_type_encoder_f NTCIPEssPaveTreatmentWidth_encode_xer;
oer_type_decoder_f NTCIPEssPaveTreatmentWidth_decode_oer;
oer_type_encoder_f NTCIPEssPaveTreatmentWidth_encode_oer;
per_type_decoder_f NTCIPEssPaveTreatmentWidth_decode_uper;
per_type_encoder_f NTCIPEssPaveTreatmentWidth_encode_uper;
per_type_decoder_f NTCIPEssPaveTreatmentWidth_decode_aper;
per_type_encoder_f NTCIPEssPaveTreatmentWidth_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NTCIPEssPaveTreatmentWidth_H_ */
#include "asn_internal.h"
