/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CooperativeControlMessage"
 * 	found in "J2945-6-CooperativeControlMessage-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_Roll_H_
#define	_Roll_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Roll */
typedef long	 Roll_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Roll_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Roll;
asn_struct_free_f Roll_free;
asn_struct_print_f Roll_print;
asn_constr_check_f Roll_constraint;
ber_type_decoder_f Roll_decode_ber;
der_type_encoder_f Roll_encode_der;
xer_type_decoder_f Roll_decode_xer;
xer_type_encoder_f Roll_encode_xer;
oer_type_decoder_f Roll_decode_oer;
oer_type_encoder_f Roll_encode_oer;
per_type_decoder_f Roll_decode_uper;
per_type_encoder_f Roll_encode_uper;
per_type_decoder_f Roll_decode_aper;
per_type_encoder_f Roll_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Roll_H_ */
#include "asn_internal.h"
