/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeDataReport"
 * 	found in "J2945-C-ProbeDataReport-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#include "RptVehicleClass.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_RptVehicleClass_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_RptVehicleClass_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  12 }	/* (0..12,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_RptVehicleClass_value2enum_1[] = {
	{ 1,	11,	"motorcycles" },
	{ 2,	13,	"passengerCars" },
	{ 3,	29,	"other2axle4tireSingleUnitVehs" },
	{ 4,	5,	"buses" },
	{ 5,	28,	"twoAxle6TireSingleUnitTrucks" },
	{ 6,	25,	"threeAxleSingleUnitTrucks" },
	{ 7,	30,	"fourOrMoreAxleSingleUnitTrucks" },
	{ 8,	34,	"fourOrFewerAxleSingleTrailerTrucks" },
	{ 9,	27,	"fiveAxleSingleTrailerTrucks" },
	{ 10,	32,	"sixOrMoreAxleSingleTrailerTrucks" },
	{ 11,	33,	"fiveOrFewerAxleMultiTrailerTrucks" },
	{ 12,	25,	"sixAxleMultiTrailerTrucks" },
	{ 13,	33,	"sevenOrMoreAxleMultiTrailerTrucks" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_RptVehicleClass_enum2value_1[] = {
	3,	/* buses(4) */
	8,	/* fiveAxleSingleTrailerTrucks(9) */
	10,	/* fiveOrFewerAxleMultiTrailerTrucks(11) */
	7,	/* fourOrFewerAxleSingleTrailerTrucks(8) */
	6,	/* fourOrMoreAxleSingleUnitTrucks(7) */
	0,	/* motorcycles(1) */
	2,	/* other2axle4tireSingleUnitVehs(3) */
	1,	/* passengerCars(2) */
	12,	/* sevenOrMoreAxleMultiTrailerTrucks(13) */
	11,	/* sixAxleMultiTrailerTrucks(12) */
	9,	/* sixOrMoreAxleSingleTrailerTrucks(10) */
	5,	/* threeAxleSingleUnitTrucks(6) */
	4	/* twoAxle6TireSingleUnitTrucks(5) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_RptVehicleClass_specs_1 = {
	asn_MAP_RptVehicleClass_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_RptVehicleClass_enum2value_1,	/* N => "tag"; sorted by N */
	13,	/* Number of elements in the maps */
	14,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_RptVehicleClass_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RptVehicleClass = {
	"RptVehicleClass",
	"RptVehicleClass",
	&asn_OP_NativeEnumerated,
	asn_DEF_RptVehicleClass_tags_1,
	sizeof(asn_DEF_RptVehicleClass_tags_1)
		/sizeof(asn_DEF_RptVehicleClass_tags_1[0]), /* 1 */
	asn_DEF_RptVehicleClass_tags_1,	/* Same as above */
	sizeof(asn_DEF_RptVehicleClass_tags_1)
		/sizeof(asn_DEF_RptVehicleClass_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_RptVehicleClass_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_RptVehicleClass_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_RptVehicleClass_specs_1	/* Additional specs */
};

