/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RoadUserChargingReportMessage"
 * 	found in "J3217-R-RoadUserChargingReportMsg-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_UserFeeInfo_H_
#define	_UserFeeInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PaymentFee.h"
#include "TimePeriod.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UserFeeInfo */
typedef struct UserFeeInfo {
	PaymentFee_t	 fee;
	TimePeriod_t	 timePeriod;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UserFeeInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UserFeeInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_UserFeeInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_UserFeeInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UserFeeInfo_H_ */
#include "asn_internal.h"
