/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RoadUserChargingReportMessage"
 * 	found in "J3217-R-RoadUserChargingReportMsg-2024-rel-v1.1.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#include "UserFeeInfo.h"

asn_TYPE_member_t asn_MBR_UserFeeInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UserFeeInfo, fee),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PaymentFee,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"fee"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UserFeeInfo, timePeriod),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimePeriod,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"timePeriod"
		},
};
static const ber_tlv_tag_t asn_DEF_UserFeeInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UserFeeInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fee */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* timePeriod */
};
asn_SEQUENCE_specifics_t asn_SPC_UserFeeInfo_specs_1 = {
	sizeof(struct UserFeeInfo),
	offsetof(struct UserFeeInfo, _asn_ctx),
	asn_MAP_UserFeeInfo_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UserFeeInfo = {
	"UserFeeInfo",
	"UserFeeInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_UserFeeInfo_tags_1,
	sizeof(asn_DEF_UserFeeInfo_tags_1)
		/sizeof(asn_DEF_UserFeeInfo_tags_1[0]), /* 1 */
	asn_DEF_UserFeeInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_UserFeeInfo_tags_1)
		/sizeof(asn_DEF_UserFeeInfo_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UserFeeInfo_1,
	2,	/* Elements count */
	&asn_SPC_UserFeeInfo_specs_1	/* Additional specs */
};

